//
// Milkyway Hierarchical Verilog Dump:
// Generated on 08/01/2016 at 17:17:44
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :ComputeUnit
// Cell Name    :ComputeUnit
// Hierarchy delimiter:'/'
// Write Command : write_verilog /local/ssd/home/tianzhao/power_estimate_eg/plasticine/scripts/CU_power_area_estimate/post_pr_gatelevel_netlist/ComputeUnit.output.v
//


module ComputeUnit (io_scalarOut , io_opcode , io_opA_local , 
    io_opA_remote , io_opB_local , io_opB_remote , clk , io_result , 
    io_opB_isLocal , io_opA_isLocal , io_rmux1 , io_rmux0 , io_done , 
    io_config_enable , io_enable , reset );
output [6:0] io_scalarOut ;
output [6:0] io_opcode ;
output [6:0] io_opA_local ;
output [6:0] io_opA_remote ;
output [6:0] io_opB_local ;
output [6:0] io_opB_remote ;
input  clk ;
output [6:0] io_result ;
output io_opB_isLocal ;
output io_opA_isLocal ;
output io_rmux1 ;
output io_rmux0 ;
output io_done ;
input  io_config_enable ;
input  io_enable ;
input  reset ;


wire [2:0] counterChain_io_data_0_out ;
wire [2:0] counterChain_io_data_1_out ;

XNR3D1BWP U16 (.ZN ( n21 ) , .A3 ( n185 ) , .A1 ( n195 ) , .A2 ( n184 ) ) ;
OA31D2BWP U275 (.Z ( n225 ) , .B ( n222 ) , .A3 ( n5 ) , .A2 ( n250 ) 
    , .A1 ( n224 ) ) ;
CKBD16BWP U12 (.Z ( io_scalarOut[2] ) , .I ( n217 ) ) ;
INVD16BWP U340 (.ZN ( io_scalarOut[1] ) , .I ( n233 ) ) ;
CKBD16BWP U9 (.Z ( io_result[0] ) , .I ( n267 ) ) ;
INVD16BWP U336 (.ZN ( io_scalarOut[0] ) , .I ( n225 ) ) ;
AN2XD1BWP U291 (.Z ( n16 ) , .A1 ( n220 ) , .A2 ( n191 ) ) ;
FA1D0BWP U319 (.CO ( n199 ) , .S ( n216 ) , .CI ( n232 ) , .B ( n210 ) 
    , .A ( n211 ) ) ;
CKBD12BWP U7 (.Z ( io_opB_remote[0] ) , .I ( n266 ) ) ;
CKBD12BWP U2 (.Z ( io_rmux1 ) , .I ( n265 ) ) ;
INVD12BWP U1 (.ZN ( io_opcode[1] ) , .I ( n250 ) ) ;
INVD12BWP U11 (.ZN ( io_done ) , .I ( n218 ) ) ;
CKBD12BWP U15 (.Z ( io_scalarOut[5] ) , .I ( n16 ) ) ;
INVD12BWP U14 (.ZN ( io_scalarOut[4] ) , .I ( n202 ) ) ;
CKBD12BWP U13 (.Z ( io_scalarOut[3] ) , .I ( n209 ) ) ;
CKND0BWP U10 (.ZN ( n10 ) , .I ( io_result[0] ) ) ;
CKND0BWP U8 (.ZN ( n8 ) , .I ( io_opB_remote[0] ) ) ;
CKND0BWP U6 (.ZN ( n6 ) , .I ( counterChain_io_data_0_out[1] ) ) ;
CKND0BWP U5 (.ZN ( n5 ) , .I ( counterChain_io_data_0_out[0] ) ) ;
CKND0BWP U4 (.ZN ( n4 ) , .I ( counterChain_io_data_0_out[2] ) ) ;
CKND0BWP U3 (.ZN ( n3 ) , .I ( io_rmux1 ) ) ;
IOA21D1BWP U322 (.ZN ( n217 ) , .B ( n215 ) , .A2 ( n216 ) , .A1 ( n191 ) ) ;
MUX2D1BWP U317 (.Z ( n209 ) , .I1 ( n207 ) , .I0 ( n208 ) , .S ( n191 ) ) ;
DFD1BWP config_pipeStage_0_opcode_reg_1_ (.QN ( n250 ) , .Q ( n191 ) 
    , .D ( N46 ) , .CP ( clk ) ) ;
OA31D1BWP U276 (.Z ( n233 ) , .B ( n230 ) , .A3 ( n250 ) , .A2 ( n231 ) 
    , .A1 ( n232 ) ) ;
OR2XD1BWP U279 (.Z ( n202 ) , .A2 ( n250 ) , .A1 ( n21 ) ) ;
NR2D1BWP U281 (.ZN ( n184 ) , .A1 ( n4 ) , .A2 ( n192 ) ) ;
MAOI222D1BWP U282 (.ZN ( n185 ) , .C ( n204 ) , .B ( n206 ) , .A ( n205 ) ) ;
MAOI222D1BWP U284 (.ZN ( n186 ) , .C ( n185 ) , .B ( n184 ) , .A ( n195 ) ) ;
CKND1BWP U285 (.ZN ( n220 ) , .I ( n186 ) ) ;
CKND2D1BWP U286 (.ZN ( n187 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( counterChain_io_data_0_out[0] ) ) ;
OAI211D1BWP U287 (.C ( n187 ) , .B ( n235 ) , .ZN ( n188 ) 
    , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( counterChain_io_data_0_out[0] ) ) ;
IOA21D1BWP U288 (.ZN ( counterChain_CounterRC_counter_reg__N7 ) , .B ( n188 ) 
    , .A2 ( n236 ) , .A1 ( counterChain_io_data_0_out[1] ) ) ;
CKND1BWP U289 (.ZN ( n189 ) , .I ( counterChain_io_data_1_out[1] ) ) ;
AOI32D1BWP U290 (.B2 ( n189 ) , .B1 ( n241 ) , .A1 ( n245 ) 
    , .A2 ( counterChain_io_data_1_out[1] ) , .A3 ( n243 ) 
    , .ZN ( counterChain_CounterRC_1_counter_reg__N7 ) ) ;
MUX2D1BWP U292 (.Z ( n213 ) , .I1 ( counterChain_io_data_1_out[2] ) 
    , .I0 ( counterChain_io_data_0_out[2] ) , .S ( io_rmux1 ) ) ;
MUX2D1BWP U293 (.Z ( n228 ) , .I1 ( counterChain_io_data_1_out[1] ) 
    , .I0 ( counterChain_io_data_0_out[1] ) , .S ( io_rmux1 ) ) ;
ND4D1BWP U294 (.ZN ( n194 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( counterChain_io_data_0_out[0] ) , .A3 ( n213 ) , .A4 ( n228 ) ) ;
CKND1BWP U296 (.ZN ( n192 ) , .I ( n213 ) ) ;
ND2D1BWP U297 (.ZN ( n193 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( n213 ) ) ;
XNR2D1BWP U298 (.ZN ( n204 ) , .A2 ( n193 ) , .A1 ( n194 ) ) ;
ND2D1BWP U299 (.ZN ( n206 ) , .A1 ( counterChain_io_data_0_out[2] ) 
    , .A2 ( n228 ) ) ;
CKND2D1BWP U300 (.ZN ( n197 ) , .A1 ( counterChain_io_data_0_out[0] ) 
    , .A2 ( n213 ) ) ;
CKND2D1BWP U301 (.ZN ( n196 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( n228 ) ) ;
CKND1BWP U302 (.ZN ( n195 ) , .I ( n194 ) ) ;
AOI21D1BWP U303 (.B ( n195 ) , .ZN ( n211 ) , .A1 ( n197 ) , .A2 ( n196 ) ) ;
CKMUX2D1BWP U304 (.Z ( n226 ) , .I1 ( counterChain_io_data_1_out[0] ) 
    , .I0 ( counterChain_io_data_0_out[0] ) , .S ( io_rmux1 ) ) ;
CKND1BWP U305 (.ZN ( n224 ) , .I ( n226 ) ) ;
NR2D1BWP U306 (.ZN ( n210 ) , .A1 ( n4 ) , .A2 ( n224 ) ) ;
NR2D1BWP U309 (.ZN ( n234 ) , .A1 ( n5 ) , .A2 ( n6 ) ) ;
AN3XD1BWP U310 (.Z ( n232 ) , .A3 ( n234 ) , .A2 ( n226 ) , .A1 ( n228 ) ) ;
CKND1BWP U311 (.ZN ( n205 ) , .I ( n199 ) ) ;
CKND2D1BWP U314 (.ZN ( n227 ) , .A1 ( n226 ) 
    , .A2 ( counterChain_io_data_0_out[0] ) ) ;
CKND1BWP U315 (.ZN ( n208 ) , .I ( n203 ) ) ;
XNR3D1BWP U316 (.ZN ( n207 ) , .A3 ( n204 ) , .A1 ( n206 ) , .A2 ( n205 ) ) ;
FICOND1BWP U320 (.S ( n214 ) , .CON ( n203 ) , .CI ( n212 ) , .B ( n213 ) 
    , .A ( counterChain_io_data_0_out[2] ) ) ;
ND2D1BWP U321 (.ZN ( n215 ) , .A1 ( n214 ) , .A2 ( n250 ) ) ;
INVD1BWP U324 (.ZN ( n238 ) , .I ( counterChain_io_data_1_out[2] ) ) ;
OR2XD1BWP U325 (.Z ( n218 ) , .A2 ( n238 ) , .A1 ( n4 ) ) ;
INVD1BWP U327 (.ZN ( n263 ) , .I ( reset ) ) ;
ND2D1BWP U328 (.ZN ( n219 ) , .A1 ( io_enable ) , .A2 ( n263 ) ) ;
NR2D1BWP U329 (.ZN ( n235 ) , .A1 ( n219 ) 
    , .A2 ( counterChain_io_data_0_out[2] ) ) ;
NR2D1BWP U330 (.ZN ( n236 ) , .A1 ( reset ) , .A2 ( io_enable ) ) ;
CKMUX2D1BWP U331 (.Z ( counterChain_CounterRC_counter_reg__N6 ) , .I1 ( n236 ) 
    , .I0 ( n235 ) , .S ( counterChain_io_data_0_out[0] ) ) ;
XOR2D1BWP U334 (.Z ( n221 ) , .A2 ( counterChain_io_data_0_out[0] ) 
    , .A1 ( n226 ) ) ;
ND2D1BWP U335 (.ZN ( n222 ) , .A1 ( n221 ) , .A2 ( n250 ) ) ;
AOI22D1BWP U337 (.A2 ( n226 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .ZN ( n231 ) , .B1 ( n228 ) , .B2 ( counterChain_io_data_0_out[0] ) ) ;
FICIND1BWP U338 (.S ( n229 ) , .CO ( n212 ) , .CIN ( n227 ) , .B ( n228 ) 
    , .A ( counterChain_io_data_0_out[1] ) ) ;
ND2D1BWP U339 (.ZN ( n230 ) , .A1 ( n229 ) , .A2 ( n250 ) ) ;
AO22D1BWP U341 (.Z ( counterChain_CounterRC_counter_reg__N8 ) , .A2 ( n234 ) 
    , .A1 ( n235 ) , .B1 ( n236 ) , .B2 ( counterChain_io_data_0_out[2] ) ) ;
AN4D1BWP U342 (.Z ( n240 ) , .A4 ( counterChain_io_data_0_out[2] ) 
    , .A3 ( n263 ) , .A2 ( n238 ) , .A1 ( io_enable ) ) ;
ND2D1BWP U343 (.ZN ( n241 ) , .A1 ( counterChain_io_data_1_out[0] ) 
    , .A2 ( n240 ) ) ;
CKND1BWP U344 (.ZN ( n239 ) , .I ( counterChain_io_data_1_out[1] ) ) ;
AOI21D1BWP U345 (.B ( n236 ) , .ZN ( n245 ) , .A1 ( n4 ) , .A2 ( n263 ) ) ;
OAI22D1BWP U346 (.B1 ( n245 ) , .B2 ( n238 ) 
    , .ZN ( counterChain_CounterRC_1_counter_reg__N8 ) , .A2 ( n239 ) 
    , .A1 ( n241 ) ) ;
INVD1BWP U350 (.ZN ( n244 ) , .I ( counterChain_io_data_1_out[0] ) ) ;
ND2D1BWP U351 (.ZN ( n243 ) , .A1 ( n240 ) , .A2 ( n244 ) ) ;
OAI21D1BWP U353 (.B ( n263 ) , .ZN ( N57 ) , .A1 ( n3 ) 
    , .A2 ( io_config_enable ) ) ;
OAI21D1BWP U354 (.B ( n243 ) 
    , .ZN ( counterChain_CounterRC_1_counter_reg__N6 ) , .A1 ( n245 ) 
    , .A2 ( n244 ) ) ;
OAI21D1BWP U355 (.B ( n263 ) , .ZN ( N46 ) , .A1 ( n250 ) 
    , .A2 ( io_config_enable ) ) ;
OAI21D1BWP U360 (.B ( n263 ) , .ZN ( N63 ) , .A1 ( io_config_enable ) 
    , .A2 ( n8 ) ) ;
OAI21D1BWP U361 (.B ( n263 ) , .ZN ( N39 ) , .A1 ( io_config_enable ) 
    , .A2 ( n10 ) ) ;
DFQD1BWP counterChain_CounterRC_1_counter_reg__ff_reg_2_ (
    .Q ( counterChain_io_data_1_out[2] ) 
    , .D ( counterChain_CounterRC_1_counter_reg__N8 ) , .CP ( clk ) ) ;
DFQD1BWP config_remoteMux1_reg (.Q ( n265 ) , .D ( N57 ) , .CP ( clk ) ) ;
DFQD1BWP counterChain_CounterRC_1_counter_reg__ff_reg_0_ (
    .Q ( counterChain_io_data_1_out[0] ) 
    , .D ( counterChain_CounterRC_1_counter_reg__N6 ) , .CP ( clk ) ) ;
DFQD1BWP counterChain_CounterRC_1_counter_reg__ff_reg_1_ (
    .Q ( counterChain_io_data_1_out[1] ) 
    , .D ( counterChain_CounterRC_1_counter_reg__N7 ) , .CP ( clk ) ) ;
DFQD1BWP counterChain_CounterRC_counter_reg__ff_reg_2_ (
    .Q ( counterChain_io_data_0_out[2] ) 
    , .D ( counterChain_CounterRC_counter_reg__N8 ) , .CP ( clk ) ) ;
DFQD1BWP counterChain_CounterRC_counter_reg__ff_reg_0_ (
    .Q ( counterChain_io_data_0_out[0] ) 
    , .D ( counterChain_CounterRC_counter_reg__N6 ) , .CP ( clk ) ) ;
DFQD1BWP counterChain_CounterRC_counter_reg__ff_reg_1_ (
    .Q ( counterChain_io_data_0_out[1] ) 
    , .D ( counterChain_CounterRC_counter_reg__N7 ) , .CP ( clk ) ) ;
DFQD1BWP config_pipeStage_0_opB_regRemote_reg (.Q ( n266 ) , .D ( N63 ) 
    , .CP ( clk ) ) ;
DFQD1BWP config_pipeStage_0_result_reg_0_ (.Q ( n267 ) , .D ( N39 ) 
    , .CP ( clk ) ) ;
assign io_opcode[2] = 1'b0;
assign io_opcode[0] = 1'b0;
assign io_scalarOut[6] = 1'b0;
assign io_opA_local[3] = 1'b0;
assign io_opA_local[2] = 1'b0;
assign io_opA_local[1] = 1'b0;
assign io_opA_local[0] = 1'b0;
assign io_opcode[6] = 1'b0;
assign io_opcode[5] = 1'b0;
assign io_opcode[4] = 1'b0;
assign io_opcode[3] = 1'b0;
assign io_opA_remote[4] = 1'b0;
assign io_opA_remote[3] = 1'b0;
assign io_opA_remote[2] = 1'b0;
assign io_opA_remote[1] = 1'b0;
assign io_opA_remote[0] = 1'b0;
assign io_opA_local[6] = 1'b0;
assign io_opA_local[5] = 1'b0;
assign io_opA_local[4] = 1'b0;
assign io_opB_local[5] = 1'b0;
assign io_opB_local[4] = 1'b0;
assign io_opB_local[3] = 1'b0;
assign io_opB_local[2] = 1'b0;
assign io_opB_local[1] = 1'b0;
assign io_opB_local[0] = 1'b0;
assign io_opA_remote[6] = 1'b0;
assign io_opA_remote[5] = 1'b0;
assign io_opB_remote[6] = 1'b0;
assign io_opB_remote[5] = 1'b0;
assign io_opB_remote[4] = 1'b0;
assign io_opB_remote[3] = 1'b0;
assign io_opB_remote[2] = 1'b0;
assign io_opB_remote[1] = 1'b0;
assign io_opB_local[6] = 1'b0;
assign io_result[6] = 1'b0;
assign io_result[5] = 1'b0;
assign io_result[4] = 1'b0;
assign io_result[3] = 1'b0;
assign io_result[2] = 1'b0;
assign io_result[1] = 1'b0;
assign io_opB_isLocal = 1'b0;
assign io_opA_isLocal = 1'b0;
assign io_rmux0 = 1'b0;
endmodule


