//
// Milkyway Hierarchical Verilog Dump:
// Generated on 07/26/2016 at 14:38:50
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :ComputeUnit
// Cell Name    :ComputeUnit
// Hierarchy delimiter:'/'
// Write Command : write_verilog /local/ssd/home/tianzhao/plasticine/scripts/CU_power_area_estimate/post_pr_gatelevel_netlist/ComputeUnit.output.v
//


module ComputeUnit (io_scalarOut , io_opcode , io_opA_local , 
    io_opA_remote , io_opB_local , io_opB_remote , clk , io_result , 
    io_opB_isLocal , io_opA_isLocal , io_rmux1 , io_rmux0 , io_done , 
    io_config_enable , io_enable , reset );
output [6:0] io_scalarOut ;
output [6:0] io_opcode ;
output [6:0] io_opA_local ;
output [6:0] io_opA_remote ;
output [6:0] io_opB_local ;
output [6:0] io_opB_remote ;
input  clk ;
output [6:0] io_result ;
output io_opB_isLocal ;
output io_opA_isLocal ;
output io_rmux1 ;
output io_rmux0 ;
output io_done ;
input  io_config_enable ;
input  io_enable ;
input  reset ;


wire [2:0] counterChain_io_data_0_out ;
wire [2:0] counterChain_io_data_1_out ;

CKBD12BWP U15 (.Z ( io_scalarOut[5] ) , .I ( n16 ) ) ;
BUFFD16BWP U14 (.Z ( io_scalarOut[3] ) , .I ( n231 ) ) ;
INVD16BWP U13 (.ZN ( io_scalarOut[2] ) , .I ( n188 ) ) ;
INVD1BWP U12 (.ZN ( n12 ) , .I ( io_opcode[1] ) ) ;
BUFFD16BWP U11 (.Z ( io_opcode[1] ) , .I ( n262 ) ) ;
CKND0BWP U10 (.ZN ( n10 ) , .I ( io_result[0] ) ) ;
BUFFD16BWP U9 (.Z ( io_result[0] ) , .I ( n264 ) ) ;
CKND0BWP U8 (.ZN ( n8 ) , .I ( io_opB_remote[0] ) ) ;
BUFFD16BWP U7 (.Z ( io_opB_remote[0] ) , .I ( n263 ) ) ;
CKND0BWP U6 (.ZN ( n6 ) , .I ( counterChain_io_data_0_out[1] ) ) ;
CKND0BWP U5 (.ZN ( n5 ) , .I ( counterChain_io_data_0_out[0] ) ) ;
CKND0BWP U4 (.ZN ( n4 ) , .I ( counterChain_io_data_0_out[2] ) ) ;
CKND0BWP U3 (.ZN ( n3 ) , .I ( io_rmux1 ) ) ;
BUFFD16BWP U2 (.Z ( io_rmux1 ) , .I ( n261 ) ) ;
CKBD1BWP U1 (.Z ( n1 ) , .I ( clk ) ) ;
MUX2D1BWP U271 (.Z ( n231 ) , .I1 ( n229 ) , .I0 ( n230 ) , .S ( io_opcode[1] ) ) ;
CKND2D1BWP U274 (.ZN ( n184 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( counterChain_io_data_0_out[0] ) ) ;
OAI211D1BWP U275 (.C ( n184 ) , .B ( n234 ) , .ZN ( n185 ) 
    , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( counterChain_io_data_0_out[0] ) ) ;
IOA21D1BWP U276 (.ZN ( counterChain_CounterRC_counter_reg__N7 ) , .B ( n185 ) 
    , .A2 ( n235 ) , .A1 ( counterChain_io_data_0_out[1] ) ) ;
CKND1BWP U277 (.ZN ( n186 ) , .I ( counterChain_io_data_1_out[1] ) ) ;
AOI32D1BWP U278 (.B2 ( n186 ) , .B1 ( n237 ) , .A1 ( n239 ) 
    , .A2 ( counterChain_io_data_1_out[1] ) , .A3 ( n240 ) 
    , .ZN ( counterChain_CounterRC_1_counter_reg__N7 ) ) ;
OR2XD1BWP U279 (.Z ( n187 ) , .A2 ( n243 ) , .A1 ( n4 ) ) ;
AN2XD1BWP U280 (.Z ( n188 ) , .A2 ( n198 ) , .A1 ( n199 ) ) ;
AN2D8BWP U281 (.Z ( n16 ) , .A1 ( n208 ) , .A2 ( io_opcode[1] ) ) ;
OA31D1BWP U282 (.Z ( n190 ) , .B ( n220 ) , .A3 ( n12 ) , .A2 ( n221 ) 
    , .A1 ( n222 ) ) ;
OA31D1BWP U283 (.Z ( n191 ) , .B ( n214 ) , .A3 ( n12 ) , .A2 ( n5 ) 
    , .A1 ( n215 ) ) ;
OR2XD1BWP U284 (.Z ( n192 ) , .A2 ( n12 ) , .A1 ( n212 ) ) ;
MUX2D1BWP U287 (.Z ( n224 ) , .I1 ( counterChain_io_data_1_out[2] ) 
    , .I0 ( counterChain_io_data_0_out[2] ) , .S ( io_rmux1 ) ) ;
ND2D1BWP U288 (.ZN ( n195 ) , .A1 ( counterChain_io_data_0_out[0] ) 
    , .A2 ( n224 ) ) ;
MUX2D1BWP U289 (.Z ( n218 ) , .I1 ( counterChain_io_data_1_out[1] ) 
    , .I0 ( counterChain_io_data_0_out[1] ) , .S ( io_rmux1 ) ) ;
ND2D1BWP U290 (.ZN ( n194 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( n218 ) ) ;
ND4D1BWP U291 (.ZN ( n204 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( counterChain_io_data_0_out[0] ) , .A3 ( n224 ) , .A4 ( n218 ) ) ;
INVD1BWP U292 (.ZN ( n193 ) , .I ( n204 ) ) ;
AOI21D1BWP U293 (.B ( n193 ) , .ZN ( n206 ) , .A1 ( n195 ) , .A2 ( n194 ) ) ;
MUX2D1BWP U295 (.Z ( n216 ) , .I1 ( counterChain_io_data_1_out[0] ) 
    , .I0 ( counterChain_io_data_0_out[0] ) , .S ( io_rmux1 ) ) ;
INVD1BWP U296 (.ZN ( n215 ) , .I ( n216 ) ) ;
NR2D1BWP U297 (.ZN ( n205 ) , .A1 ( n4 ) , .A2 ( n215 ) ) ;
NR2D1BWP U300 (.ZN ( n233 ) , .A1 ( n5 ) , .A2 ( n6 ) ) ;
AN3XD1BWP U301 (.Z ( n222 ) , .A3 ( n216 ) , .A2 ( n218 ) , .A1 ( n233 ) ) ;
CKND2D1BWP U302 (.ZN ( n199 ) , .A1 ( io_opcode[1] ) , .A2 ( n196 ) ) ;
ND2D1BWP U303 (.ZN ( n217 ) , .A1 ( n216 ) 
    , .A2 ( counterChain_io_data_0_out[0] ) ) ;
CKND2D1BWP U304 (.ZN ( n198 ) , .A1 ( n197 ) , .A2 ( n12 ) ) ;
INVD1BWP U307 (.ZN ( n243 ) , .I ( counterChain_io_data_1_out[2] ) ) ;
INVD12BWP U308 (.ZN ( io_done ) , .I ( n187 ) ) ;
INVD1BWP U310 (.ZN ( n202 ) , .I ( n224 ) ) ;
NR2D1BWP U311 (.ZN ( n210 ) , .A1 ( n4 ) , .A2 ( n202 ) ) ;
ND2D1BWP U312 (.ZN ( n203 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .A2 ( n224 ) ) ;
XNR2D1BWP U313 (.ZN ( n226 ) , .A2 ( n203 ) , .A1 ( n204 ) ) ;
ND2D1BWP U314 (.ZN ( n228 ) , .A1 ( counterChain_io_data_0_out[2] ) 
    , .A2 ( n218 ) ) ;
FA1D1BWP U315 (.CO ( n207 ) , .S ( n196 ) , .CI ( n222 ) , .B ( n205 ) 
    , .A ( n206 ) ) ;
INVD1BWP U316 (.ZN ( n227 ) , .I ( n207 ) ) ;
MAOI222D1BWP U317 (.ZN ( n209 ) , .C ( n227 ) , .B ( n228 ) , .A ( n226 ) ) ;
FA1D0BWP U318 (.CO ( n208 ) , .S ( n211 ) , .CI ( n209 ) , .B ( n210 ) 
    , .A ( n193 ) ) ;
INVD1BWP U319 (.ZN ( n212 ) , .I ( n211 ) ) ;
INVD12BWP U320 (.ZN ( io_scalarOut[4] ) , .I ( n192 ) ) ;
XOR2D1BWP U321 (.Z ( n213 ) , .A2 ( counterChain_io_data_0_out[0] ) 
    , .A1 ( n216 ) ) ;
ND2D1BWP U322 (.ZN ( n214 ) , .A1 ( n213 ) , .A2 ( n12 ) ) ;
INVD12BWP U323 (.ZN ( io_scalarOut[0] ) , .I ( n191 ) ) ;
AOI22D1BWP U324 (.A2 ( n216 ) , .A1 ( counterChain_io_data_0_out[1] ) 
    , .ZN ( n221 ) , .B1 ( counterChain_io_data_0_out[0] ) , .B2 ( n218 ) ) ;
FICIND1BWP U325 (.S ( n219 ) , .CO ( n223 ) , .CIN ( n217 ) , .B ( n218 ) 
    , .A ( counterChain_io_data_0_out[1] ) ) ;
ND2D1BWP U326 (.ZN ( n220 ) , .A1 ( n219 ) , .A2 ( n12 ) ) ;
INVD16BWP U327 (.ZN ( io_scalarOut[1] ) , .I ( n190 ) ) ;
FICOND1BWP U328 (.S ( n197 ) , .CON ( n225 ) , .CI ( n223 ) , .B ( n224 ) 
    , .A ( counterChain_io_data_0_out[2] ) ) ;
INVD1BWP U329 (.ZN ( n230 ) , .I ( n225 ) ) ;
XNR3D1BWP U330 (.ZN ( n229 ) , .A3 ( n226 ) , .A1 ( n228 ) , .A2 ( n227 ) ) ;
INVD1BWP U339 (.ZN ( n249 ) , .I ( reset ) ) ;
AN4D1BWP U340 (.Z ( n236 ) , .A4 ( counterChain_io_data_0_out[2] ) 
    , .A3 ( n249 ) , .A2 ( n243 ) , .A1 ( io_enable ) ) ;
ND2D1BWP U341 (.ZN ( n237 ) , .A1 ( counterChain_io_data_1_out[0] ) 
    , .A2 ( n236 ) ) ;
INVD1BWP U342 (.ZN ( n242 ) , .I ( counterChain_io_data_1_out[1] ) ) ;
NR2D1BWP U343 (.ZN ( n235 ) , .A1 ( reset ) , .A2 ( io_enable ) ) ;
AOI21D1BWP U344 (.B ( n235 ) , .ZN ( n240 ) , .A1 ( n4 ) , .A2 ( n249 ) ) ;
OAI22D1BWP U345 (.B1 ( n240 ) , .B2 ( n243 ) 
    , .ZN ( counterChain_CounterRC_1_counter_reg__N8 ) , .A2 ( n242 ) 
    , .A1 ( n237 ) ) ;
ND2D1BWP U346 (.ZN ( n232 ) , .A1 ( io_enable ) , .A2 ( n249 ) ) ;
NR2D1BWP U347 (.ZN ( n234 ) , .A1 ( n232 ) 
    , .A2 ( counterChain_io_data_0_out[2] ) ) ;
AO22D1BWP U348 (.Z ( counterChain_CounterRC_counter_reg__N8 ) , .A2 ( n234 ) 
    , .A1 ( n233 ) , .B1 ( n235 ) , .B2 ( counterChain_io_data_0_out[2] ) ) ;
MUX2D1BWP U349 (.Z ( counterChain_CounterRC_counter_reg__N6 ) , .I1 ( n235 ) 
    , .I0 ( n234 ) , .S ( counterChain_io_data_0_out[0] ) ) ;
INVD1BWP U351 (.ZN ( n241 ) , .I ( counterChain_io_data_1_out[0] ) ) ;
ND2D1BWP U352 (.ZN ( n239 ) , .A1 ( n236 ) , .A2 ( n241 ) ) ;
OAI21D1BWP U354 (.B ( n249 ) , .ZN ( N57 ) , .A1 ( io_config_enable ) 
    , .A2 ( n3 ) ) ;
OAI21D1BWP U355 (.B ( n239 ) 
    , .ZN ( counterChain_CounterRC_1_counter_reg__N6 ) , .A1 ( n240 ) 
    , .A2 ( n241 ) ) ;
OAI21D1BWP U356 (.B ( n249 ) , .ZN ( N46 ) , .A1 ( io_config_enable ) 
    , .A2 ( n12 ) ) ;
OAI21D1BWP U366 (.B ( n249 ) , .ZN ( N63 ) , .A1 ( io_config_enable ) 
    , .A2 ( n8 ) ) ;
OAI21D1BWP U367 (.B ( n249 ) , .ZN ( N39 ) , .A1 ( io_config_enable ) 
    , .A2 ( n10 ) ) ;
DFQD1BWP counterChain_CounterRC_1_counter_reg__ff_reg_2_ (
    .Q ( counterChain_io_data_1_out[2] ) 
    , .D ( counterChain_CounterRC_1_counter_reg__N8 ) , .CP ( n1 ) ) ;
DFQD1BWP config_remoteMux1_reg (.Q ( n261 ) , .D ( N57 ) , .CP ( n1 ) ) ;
DFQD1BWP counterChain_CounterRC_1_counter_reg__ff_reg_0_ (
    .Q ( counterChain_io_data_1_out[0] ) 
    , .D ( counterChain_CounterRC_1_counter_reg__N6 ) , .CP ( n1 ) ) ;
DFQD1BWP counterChain_CounterRC_1_counter_reg__ff_reg_1_ (
    .Q ( counterChain_io_data_1_out[1] ) 
    , .D ( counterChain_CounterRC_1_counter_reg__N7 ) , .CP ( n1 ) ) ;
DFQD1BWP counterChain_CounterRC_counter_reg__ff_reg_2_ (
    .Q ( counterChain_io_data_0_out[2] ) 
    , .D ( counterChain_CounterRC_counter_reg__N8 ) , .CP ( n1 ) ) ;
DFQD1BWP counterChain_CounterRC_counter_reg__ff_reg_0_ (
    .Q ( counterChain_io_data_0_out[0] ) 
    , .D ( counterChain_CounterRC_counter_reg__N6 ) , .CP ( n1 ) ) ;
DFQD1BWP counterChain_CounterRC_counter_reg__ff_reg_1_ (
    .Q ( counterChain_io_data_0_out[1] ) 
    , .D ( counterChain_CounterRC_counter_reg__N7 ) , .CP ( n1 ) ) ;
DFQD1BWP config_pipeStage_0_opB_regRemote_reg (.Q ( n263 ) , .D ( N63 ) 
    , .CP ( n1 ) ) ;
DFQD1BWP config_pipeStage_0_result_reg_0_ (.Q ( n264 ) , .D ( N39 ) 
    , .CP ( n1 ) ) ;
DFQD1BWP config_pipeStage_0_opcode_reg_1_ (.Q ( n262 ) , .D ( N46 ) 
    , .CP ( n1 ) ) ;
assign io_opcode[2] = 1'b0;
assign io_opcode[0] = 1'b0;
assign io_scalarOut[6] = 1'b0;
assign io_opA_local[3] = 1'b0;
assign io_opA_local[2] = 1'b0;
assign io_opA_local[1] = 1'b0;
assign io_opA_local[0] = 1'b0;
assign io_opcode[6] = 1'b0;
assign io_opcode[5] = 1'b0;
assign io_opcode[4] = 1'b0;
assign io_opcode[3] = 1'b0;
assign io_opA_remote[4] = 1'b0;
assign io_opA_remote[3] = 1'b0;
assign io_opA_remote[2] = 1'b0;
assign io_opA_remote[1] = 1'b0;
assign io_opA_remote[0] = 1'b0;
assign io_opA_local[6] = 1'b0;
assign io_opA_local[5] = 1'b0;
assign io_opA_local[4] = 1'b0;
assign io_opB_local[5] = 1'b0;
assign io_opB_local[4] = 1'b0;
assign io_opB_local[3] = 1'b0;
assign io_opB_local[2] = 1'b0;
assign io_opB_local[1] = 1'b0;
assign io_opB_local[0] = 1'b0;
assign io_opA_remote[6] = 1'b0;
assign io_opA_remote[5] = 1'b0;
assign io_opB_remote[6] = 1'b0;
assign io_opB_remote[5] = 1'b0;
assign io_opB_remote[4] = 1'b0;
assign io_opB_remote[3] = 1'b0;
assign io_opB_remote[2] = 1'b0;
assign io_opB_remote[1] = 1'b0;
assign io_opB_local[6] = 1'b0;
assign io_result[6] = 1'b0;
assign io_result[5] = 1'b0;
assign io_result[4] = 1'b0;
assign io_result[3] = 1'b0;
assign io_result[2] = 1'b0;
assign io_result[1] = 1'b0;
assign io_opB_isLocal = 1'b0;
assign io_opA_isLocal = 1'b0;
assign io_rmux0 = 1'b0;
endmodule


