//
// Milkyway Hierarchical Verilog Dump:
// Generated on 08/06/2016 at 19:54:50
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :Plasticine
// Cell Name    :Plasticine
// Hierarchy delimiter:'/'
// Write Command : write_verilog /local/ssd/home/tianzhao/power_estimate_eg/plasticine/scripts/CU_power_area_estimate/post_pr_gatelevel_netlist/Plasticine.output.v
//


module SNPS_CLOCK_GATE_HIGH_Crossbar_1_0_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_8 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module Plasticine (io_status , io_command , io_config_enable , reset , 
    clk );
output io_status ;
input  io_command ;
input  io_config_enable ;
input  reset ;
input  clk ;




SNPS_CLOCK_GATE_HIGH_Crossbar_1_0_1 cu0_controlBlock_incXbar_clk_gate_config__outSelect_3_reg (
    .CLK ( clk ) , .EN ( cu0_controlBlock_incXbar_net4496 ) , 
    .TE ( 1'b0 ), .ENCLK ( cu0_controlBlock_incXbar_net4499 ) ) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_8 cu1_RegisterBlock_1_FF_1_clk_gate_ff_reg (
    .CLK ( clk_G1IP ) , .EN ( cu1_RegisterBlock_1_FF_1_net4388 ) , 
    .TE ( 1'b0 ), .ENCLK ( cu1_RegisterBlock_1_FF_1_net4415 ) ) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_1 cu1_counterChain_CounterRC_1_counter_reg__clk_gate_ff_reg (
    .CLK ( clk_G1IP ) , .EN ( reset ) , .TE ( 1'b0 ), 
    .ENCLK ( cu1_counterChain_CounterRC_1_counter_reg__net4415 ) ) ;

CKBD16BWP CKBD16BWP_G1IP (.Z ( clk_G1IP ) , .I ( clk ) ) ;
CKND1BWP U2 (.ZN ( n2 ) , .I ( reset ) ) ;
IND2D1BWP U744 (.ZN ( cu0_controlBlock_incXbar_net4496 ) , .B1 ( n2 ) 
    , .A1 ( io_config_enable ) ) ;
CKND1BWP U644 (.ZN ( cu1_RegisterBlock_1_FF_1_net4388 ) , .I ( n298 ) ) ;
INR2D1BWP U408 (.B1 ( cu0_T21_0_ ) , .ZN ( n298 ) , .A1 ( n2 ) ) ;
DFQD4BWP cu0_config__pipeStage_1_opB_value_reg_0_ (.Q ( cu0_T21_0_ ) 
    , .D ( reset ) , .CP ( cu0_controlBlock_incXbar_net4499 ) ) ;
assign io_status = 1'b0;
endmodule


