//
// Milkyway Hierarchical Verilog Dump:
// Generated on 08/06/2016 at 18:03:37
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :Plasticine
// Cell Name    :Plasticine
// Hierarchy delimiter:'/'
// Write Command : write_verilog /local/ssd/home/tianzhao/power_estimate_eg/plasticine/scripts/CU_power_area_estimate/post_pr_gatelevel_netlist/Plasticine.output.v
//


module SNPS_CLOCK_GATE_HIGH_SRAM_0_27 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_28 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_29 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_30 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_31 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_32 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_33 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_16 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_18 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_19 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_21 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_23 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_24 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_25 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_26 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_8 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_9 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_10 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_11 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_12 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_13 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_14 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_15 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD6BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_8 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_Crossbar_1_0_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD12BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_2 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_4 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_6 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_7 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module Plasticine (io_status , io_command , io_config_enable , reset , 
    clk );
output io_status ;
input  io_command ;
input  io_config_enable ;
input  reset ;
input  clk ;




SNPS_CLOCK_GATE_HIGH_SRAM_0_27 cu0_mem1_clk_gate_mem_reg_6_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N21 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_28 cu0_mem1_clk_gate_mem_reg_5_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N20 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_29 cu0_mem1_clk_gate_mem_reg_4_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N19 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_30 cu0_mem1_clk_gate_mem_reg_3_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N18 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_31 cu0_mem1_clk_gate_mem_reg_2_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N17 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_32 cu0_mem1_clk_gate_mem_reg_1_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N16 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_33 cu0_mem1_clk_gate_mem_reg_0_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N15 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_16 cu1_mem0_clk_gate_mem_reg_0_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N15 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_18 cu0_mem1_clk_gate_mem_reg_15_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N30 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_19 cu0_mem1_clk_gate_mem_reg_14_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N29 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_21 cu0_mem1_clk_gate_mem_reg_12_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N27 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_23 cu0_mem1_clk_gate_mem_reg_10_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N25 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_24 cu0_mem1_clk_gate_mem_reg_9_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N24 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_25 cu0_mem1_clk_gate_mem_reg_8_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N23 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_26 cu0_mem1_clk_gate_mem_reg_7_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N22 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_8 cu1_mem0_clk_gate_mem_reg_8_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N23 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_9 cu1_mem0_clk_gate_mem_reg_7_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N22 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_10 cu1_mem0_clk_gate_mem_reg_6_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N21 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_11 cu1_mem0_clk_gate_mem_reg_5_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N20 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_12 cu1_mem0_clk_gate_mem_reg_4_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N19 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_13 cu1_mem0_clk_gate_mem_reg_3_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N18 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_14 cu1_mem0_clk_gate_mem_reg_2_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N17 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_15 cu1_mem0_clk_gate_mem_reg_1_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N16 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_1 cu1_counterChain_CounterRC_1_counter_reg__clk_gate_ff_reg (
    .CLK ( CTS_ideal_clock1_CTO_delay11 ) , .EN ( n1 ) , .TE ( 1'b0 ), 
    .ENCLK ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_8 cu1_RegisterBlock_1_FF_1_clk_gate_ff_reg (
    .CLK ( clk_G1IP ) , .EN ( cu0_RegisterBlock_1_FF_1_net3491 ) , 
    .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_Crossbar_1_0_1 cu0_controlBlock_incXbar_clk_gate_config__outSelect_3_reg (
    .CLK ( CTS_ideal_clock1_CTO_delay11 ) , 
    .EN ( cu0_controlBlock_incXbar_net3599 ) , .TE ( 1'b0 ), 
    .ENCLK ( cu0_controlBlock_incXbar_net3602 ) ) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_1 cu1_mem0_clk_gate_mem_reg_15_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N30 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_2 cu1_mem0_clk_gate_mem_reg_14_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N29 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_4 cu1_mem0_clk_gate_mem_reg_12_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N27 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_6 cu1_mem0_clk_gate_mem_reg_10_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N25 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_7 cu1_mem0_clk_gate_mem_reg_9_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N24 ) , .TE ( 1'b0 )) ;

DCCKBD16BWP CTS_ideal_clock1_CTO_delay1 (.Z ( CTS_ideal_clock1_CTO_delay11 ) 
    , .I ( clk ) ) ;
CKBD16BWP CKBD16BWP_G1IP (.Z ( clk_G1IP ) , .I ( clk ) ) ;
INVD3BWP U3 (.ZN ( n3 ) , .I ( cu0_T21_0_ ) ) ;
INVD1BWP U2 (.ZN ( n2 ) , .I ( n1 ) ) ;
CKBD2BWP U1 (.Z ( n1 ) , .I ( reset ) ) ;
ND3D1BWP U1723 (.ZN ( n897 ) 
    , .A1 ( cu1_counterChain_CounterRC_config__stride_0_ ) , .A2 ( n2 ) 
    , .A3 ( n894 ) ) ;
NR2D1BWP U1724 (.ZN ( cu0_counterChain_CounterRC_counter_reg__net3515 ) 
    , .A1 ( n897 ) , .A2 ( cu0_counterChain_io_data_0_out_0_ ) ) ;
AOI221D1BWP U1725 (.C ( n897 ) , .B1 ( n896 ) , .B2 ( n895 ) 
    , .A2 ( cu0_counterChain_io_data_0_out_1_ ) 
    , .ZN ( cu0_counterChain_CounterRC_counter_reg__net3512 ) 
    , .A1 ( cu0_counterChain_io_data_0_out_0_ ) ) ;
CKND2D1BWP U1726 (.ZN ( n898 ) , .A1 ( cu0_counterChain_io_data_0_out_0_ ) 
    , .A2 ( cu0_counterChain_io_data_0_out_1_ ) ) ;
NR2D1BWP U1727 (.ZN ( cu0_counterChain_CounterRC_counter_reg__net3509 ) 
    , .A1 ( n898 ) , .A2 ( n897 ) ) ;
NR2D1BWP U1728 (.ZN ( cu0_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .A1 ( n901 ) , .A2 ( cu0_counterChain_io_data_1_out_0_ ) ) ;
AOI221D1BWP U1729 (.C ( n901 ) , .B1 ( n900 ) , .B2 ( n899 ) 
    , .A2 ( cu0_counterChain_io_data_1_out_1_ ) 
    , .ZN ( cu0_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .A1 ( cu0_counterChain_io_data_1_out_0_ ) ) ;
CKND2D1BWP U1730 (.ZN ( n902 ) , .A1 ( cu0_counterChain_io_data_1_out_0_ ) 
    , .A2 ( cu0_counterChain_io_data_1_out_1_ ) ) ;
NR2D1BWP U1731 (.ZN ( cu0_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .A1 ( n902 ) , .A2 ( n901 ) ) ;
ND3D1BWP U1732 (.ZN ( n906 ) 
    , .A1 ( cu1_counterChain_CounterRC_config__stride_0_ ) , .A2 ( n2 ) 
    , .A3 ( n903 ) ) ;
NR2D1BWP U1733 (.ZN ( cu1_counterChain_CounterRC_counter_reg__net3515 ) 
    , .A1 ( n906 ) , .A2 ( cu1_counterChain_io_data_0_out_0_ ) ) ;
AOI221D1BWP U1734 (.C ( n906 ) , .B1 ( n905 ) , .B2 ( n904 ) 
    , .A2 ( cu1_counterChain_io_data_0_out_1_ ) 
    , .ZN ( cu1_counterChain_CounterRC_counter_reg__net3512 ) 
    , .A1 ( cu1_counterChain_io_data_0_out_0_ ) ) ;
CKND2D1BWP U1735 (.ZN ( n907 ) , .A1 ( cu1_counterChain_io_data_0_out_0_ ) 
    , .A2 ( cu1_counterChain_io_data_0_out_1_ ) ) ;
NR2D1BWP U1736 (.ZN ( cu1_counterChain_CounterRC_counter_reg__net3509 ) 
    , .A1 ( n907 ) , .A2 ( n906 ) ) ;
NR2D1BWP U1737 (.ZN ( cu1_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .A1 ( n910 ) , .A2 ( cu1_counterChain_io_data_1_out_0_ ) ) ;
AOI221D1BWP U1738 (.C ( n910 ) , .B1 ( n909 ) , .B2 ( n908 ) 
    , .A2 ( cu1_counterChain_io_data_1_out_1_ ) 
    , .ZN ( cu1_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .A1 ( cu1_counterChain_io_data_1_out_0_ ) ) ;
CKND2D1BWP U1739 (.ZN ( n911 ) , .A1 ( cu1_counterChain_io_data_1_out_0_ ) 
    , .A2 ( cu1_counterChain_io_data_1_out_1_ ) ) ;
NR2D1BWP U1740 (.ZN ( cu1_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .A1 ( n911 ) , .A2 ( n910 ) ) ;
ND2D1BWP U1741 (.ZN ( n914 ) , .A1 ( n915 ) , .A2 ( n917 ) ) ;
ND2D1BWP U1742 (.ZN ( n920 ) , .A1 ( n912 ) , .A2 ( n913 ) ) ;
NR2D1BWP U1743 (.ZN ( cu0_mem0_N15 ) , .A1 ( n914 ) , .A2 ( n920 ) ) ;
ND2D1BWP U1744 (.ZN ( n918 ) , .A1 ( n912 ) , .A2 ( n1430 ) ) ;
NR2D1BWP U1745 (.ZN ( cu0_mem0_N16 ) , .A1 ( n918 ) , .A2 ( n914 ) ) ;
ND2D1BWP U1746 (.ZN ( n921 ) , .A1 ( n1431 ) , .A2 ( n913 ) ) ;
NR2D1BWP U1747 (.ZN ( cu0_mem0_N17 ) , .A1 ( n921 ) , .A2 ( n914 ) ) ;
ND2D1BWP U1748 (.ZN ( n922 ) , .A1 ( n1431 ) , .A2 ( n1430 ) ) ;
NR2D1BWP U1749 (.ZN ( cu0_mem0_N18 ) , .A1 ( n922 ) , .A2 ( n914 ) ) ;
ND2D1BWP U1750 (.ZN ( n916 ) , .A1 ( n915 ) , .A2 ( n1432 ) ) ;
NR2D1BWP U1751 (.ZN ( cu0_mem0_N19 ) , .A1 ( n916 ) , .A2 ( n920 ) ) ;
NR2D1BWP U1752 (.ZN ( cu0_mem0_N20 ) , .A1 ( n916 ) , .A2 ( n918 ) ) ;
NR2D1BWP U1753 (.ZN ( cu0_mem0_N21 ) , .A1 ( n916 ) , .A2 ( n921 ) ) ;
NR2D1BWP U1754 (.ZN ( cu0_mem0_N22 ) , .A1 ( n916 ) , .A2 ( n922 ) ) ;
ND2D1BWP U1755 (.ZN ( n919 ) , .A1 ( n1433 ) , .A2 ( n917 ) ) ;
NR2D1BWP U1756 (.ZN ( cu0_mem0_N23 ) , .A1 ( n919 ) , .A2 ( n920 ) ) ;
NR2D1BWP U1757 (.ZN ( cu0_mem0_N24 ) , .A1 ( n919 ) , .A2 ( n918 ) ) ;
NR2D1BWP U1758 (.ZN ( cu0_mem0_N25 ) , .A1 ( n919 ) , .A2 ( n921 ) ) ;
ND2D1BWP U1759 (.ZN ( n923 ) , .A1 ( n1433 ) , .A2 ( n1432 ) ) ;
NR2D1BWP U1760 (.ZN ( cu0_mem0_N27 ) , .A1 ( n923 ) , .A2 ( n920 ) ) ;
NR2D1BWP U1761 (.ZN ( cu0_mem0_N29 ) , .A1 ( n923 ) , .A2 ( n921 ) ) ;
NR2D1BWP U1762 (.ZN ( cu0_mem0_N30 ) , .A1 ( n923 ) , .A2 ( n922 ) ) ;
ND2D1BWP U1763 (.ZN ( n926 ) , .A1 ( n927 ) , .A2 ( n929 ) ) ;
ND2D1BWP U1764 (.ZN ( n932 ) , .A1 ( n924 ) , .A2 ( n925 ) ) ;
NR2D1BWP U1765 (.ZN ( cu1_mem1_N15 ) , .A1 ( n926 ) , .A2 ( n932 ) ) ;
ND2D1BWP U1766 (.ZN ( n930 ) , .A1 ( n924 ) , .A2 ( n1434 ) ) ;
NR2D1BWP U1767 (.ZN ( cu1_mem1_N16 ) , .A1 ( n930 ) , .A2 ( n926 ) ) ;
ND2D1BWP U1768 (.ZN ( n933 ) , .A1 ( n1435 ) , .A2 ( n925 ) ) ;
NR2D1BWP U1769 (.ZN ( cu1_mem1_N17 ) , .A1 ( n933 ) , .A2 ( n926 ) ) ;
ND2D1BWP U1770 (.ZN ( n934 ) , .A1 ( n1435 ) , .A2 ( n1434 ) ) ;
NR2D1BWP U1771 (.ZN ( cu1_mem1_N18 ) , .A1 ( n934 ) , .A2 ( n926 ) ) ;
ND2D1BWP U1772 (.ZN ( n928 ) , .A1 ( n927 ) , .A2 ( n1436 ) ) ;
NR2D1BWP U1773 (.ZN ( cu1_mem1_N19 ) , .A1 ( n928 ) , .A2 ( n932 ) ) ;
NR2D1BWP U1774 (.ZN ( cu1_mem1_N20 ) , .A1 ( n928 ) , .A2 ( n930 ) ) ;
NR2D1BWP U1775 (.ZN ( cu1_mem1_N21 ) , .A1 ( n928 ) , .A2 ( n933 ) ) ;
NR2D1BWP U1776 (.ZN ( cu1_mem1_N22 ) , .A1 ( n928 ) , .A2 ( n934 ) ) ;
ND2D1BWP U1777 (.ZN ( n931 ) , .A1 ( n1437 ) , .A2 ( n929 ) ) ;
NR2D1BWP U1778 (.ZN ( cu1_mem1_N23 ) , .A1 ( n931 ) , .A2 ( n932 ) ) ;
NR2D1BWP U1779 (.ZN ( cu1_mem1_N24 ) , .A1 ( n931 ) , .A2 ( n930 ) ) ;
NR2D1BWP U1780 (.ZN ( cu1_mem1_N25 ) , .A1 ( n931 ) , .A2 ( n933 ) ) ;
ND2D1BWP U1781 (.ZN ( n935 ) , .A1 ( n1437 ) , .A2 ( n1436 ) ) ;
NR2D1BWP U1782 (.ZN ( cu1_mem1_N27 ) , .A1 ( n935 ) , .A2 ( n932 ) ) ;
NR2D1BWP U1784 (.ZN ( cu1_mem1_N29 ) , .A1 ( n935 ) , .A2 ( n933 ) ) ;
NR2D1BWP U1785 (.ZN ( cu1_mem1_N30 ) , .A1 ( n935 ) , .A2 ( n934 ) ) ;
FICIND1BWP U1630 (.S ( n815 ) , .CO ( n832 ) , .CIN ( n816 ) , .B ( n811 ) 
    , .A ( n812 ) ) ;
HICOND1BWP U1631 (.S ( n870 ) , .A ( n814 ) , .CI ( n813 ) , .CON ( n784 ) ) ;
CKMUX2D1BWP U1632 (.Z ( n1435 ) , .I1 ( n870 ) , .I0 ( n815 ) 
    , .S ( cu0_T21_0_ ) ) ;
NR2D1BWP U1633 (.ZN ( n869 ) , .A1 ( n747 ) , .A2 ( n816 ) ) ;
CKND2D1BWP U1634 (.ZN ( n925 ) , .A1 ( n869 ) , .A2 ( cu0_T21_0_ ) ) ;
CKND1BWP U1635 (.ZN ( n1434 ) , .I ( n925 ) ) ;
FICIND1BWP U1636 (.S ( n823 ) , .CO ( n837 ) , .CIN ( n827 ) , .B ( n819 ) 
    , .A ( n820 ) ) ;
HICOND1BWP U1637 (.S ( n867 ) , .A ( n822 ) , .CI ( n821 ) , .CON ( n802 ) ) ;
CKMUX2D1BWP U1638 (.Z ( n1431 ) , .I1 ( n867 ) , .I0 ( n823 ) 
    , .S ( cu0_T21_0_ ) ) ;
NR2D1BWP U1640 (.ZN ( n866 ) , .A1 ( n827 ) , .A2 ( n748 ) ) ;
CKND2D1BWP U1641 (.ZN ( n913 ) , .A1 ( n866 ) , .A2 ( cu0_T21_0_ ) ) ;
CKND1BWP U1642 (.ZN ( n1430 ) , .I ( n913 ) ) ;
FICOND1BWP U1646 (.S ( n783 ) , .CON ( n846 ) , .CI ( n832 ) , .B ( n833 ) 
    , .A ( n834 ) ) ;
MUX2D1BWP U1647 (.Z ( n1437 ) , .I1 ( n843 ) , .I0 ( n836 ) , .S ( cu0_T21_0_ ) ) ;
FICOND1BWP U1648 (.S ( n801 ) , .CON ( n849 ) , .CI ( n837 ) , .B ( n838 ) 
    , .A ( n839 ) ) ;
MUX2D1BWP U1649 (.Z ( n1433 ) , .I1 ( n845 ) , .I0 ( n842 ) , .S ( cu0_T21_0_ ) ) ;
NR2D1BWP U1650 (.ZN ( cu0_RegisterBlock_FF_1_net3515 ) , .A1 ( n1 ) 
    , .A2 ( n913 ) ) ;
NR2D1BWP U1651 (.ZN ( cu1_RegisterBlock_FF_1_net3515 ) , .A1 ( n1 ) 
    , .A2 ( n925 ) ) ;
INVD1BWP U1652 (.ZN ( n912 ) , .I ( n1431 ) ) ;
NR2D1BWP U1653 (.ZN ( cu0_RegisterBlock_FF_1_net3512 ) , .A1 ( n1 ) 
    , .A2 ( n912 ) ) ;
INVD1BWP U1655 (.ZN ( n924 ) , .I ( n1435 ) ) ;
NR2D1BWP U1656 (.ZN ( cu1_RegisterBlock_FF_1_net3512 ) , .A1 ( n1 ) 
    , .A2 ( n924 ) ) ;
CKND1BWP U1657 (.ZN ( n917 ) , .I ( n1432 ) ) ;
NR2D1BWP U1658 (.ZN ( cu0_RegisterBlock_FF_1_net3509 ) , .A1 ( n1 ) 
    , .A2 ( n917 ) ) ;
CKND1BWP U1659 (.ZN ( n929 ) , .I ( n1436 ) ) ;
NR2D1BWP U1660 (.ZN ( cu1_RegisterBlock_FF_1_net3509 ) , .A1 ( n1 ) 
    , .A2 ( n929 ) ) ;
INVD1BWP U1665 (.ZN ( n927 ) , .I ( n1437 ) ) ;
FICIND1BWP U1667 (.S ( n842 ) , .CIN ( n849 ) , .B ( n749 ) , .A ( n749 ) ) ;
INVD1BWP U1669 (.ZN ( n915 ) , .I ( n1433 ) ) ;
NR2D1BWP U1670 (.ZN ( cu0_RegisterBlock_FF_1_net3506 ) , .A1 ( n1 ) 
    , .A2 ( n915 ) ) ;
IND2D1BWP U1680 (.ZN ( cu0_controlBlock_incXbar_net3599 ) , .B1 ( n2 ) 
    , .A1 ( io_config_enable ) ) ;
OA21D1BWP U1067 (.Z ( n747 ) , .B ( n754 ) , .A1 ( n3 ) , .A2 ( n905 ) ) ;
OA21D1BWP U1068 (.Z ( n748 ) , .B ( n792 ) , .A1 ( n3 ) , .A2 ( n900 ) ) ;
AN2XD1BWP U1069 (.Z ( n749 ) , .A2 ( cu0_RegisterBlock_FF_io_data_out_3_ ) 
    , .A1 ( n3 ) ) ;
ND2D1BWP U1548 (.ZN ( cu0_RegisterBlock_1_FF_1_net3491 ) , .A1 ( n2 ) 
    , .A2 ( n3 ) ) ;
INVD1BWP U1551 (.ZN ( n903 ) , .I ( cu1_counterChain_io_data_0_out_2_ ) ) ;
ND2D1BWP U1552 (.ZN ( n750 ) , .A1 ( n3 ) 
    , .A2 ( cu1_RegisterBlock_FF_io_data_out_2_ ) ) ;
OAI21D1BWP U1553 (.B ( n750 ) , .ZN ( n834 ) , .A1 ( n3 ) , .A2 ( n903 ) ) ;
INVD1BWP U1554 (.ZN ( n755 ) , .I ( n834 ) ) ;
IOA21D1BWP U1555 (.ZN ( n833 ) , .B ( n750 ) 
    , .A2 ( cu1_counterChain_io_data_1_out_2_ ) , .A1 ( cu0_T21_0_ ) ) ;
INVD1BWP U1556 (.ZN ( n752 ) , .I ( n833 ) ) ;
INVD1BWP U1558 (.ZN ( n908 ) , .I ( cu1_counterChain_io_data_1_out_1_ ) ) ;
ND2D1BWP U1559 (.ZN ( n751 ) , .A1 ( n3 ) 
    , .A2 ( cu1_RegisterBlock_FF_io_data_out_1_ ) ) ;
OAI21D1BWP U1560 (.B ( n751 ) , .ZN ( n811 ) , .A1 ( n3 ) , .A2 ( n908 ) ) ;
INVD1BWP U1561 (.ZN ( n759 ) , .I ( n811 ) ) ;
INVD1BWP U1562 (.ZN ( n905 ) , .I ( cu1_counterChain_io_data_0_out_0_ ) ) ;
ND2D1BWP U1563 (.ZN ( n754 ) , .A1 ( n3 ) 
    , .A2 ( cu1_RegisterBlock_FF_io_data_out_0_ ) ) ;
NR2D1BWP U1564 (.ZN ( n757 ) , .A1 ( n747 ) , .A2 ( n752 ) ) ;
INVD1BWP U1565 (.ZN ( n904 ) , .I ( cu1_counterChain_io_data_0_out_1_ ) ) ;
OAI21D1BWP U1566 (.B ( n751 ) , .ZN ( n812 ) , .A1 ( n3 ) , .A2 ( n904 ) ) ;
INVD1BWP U1567 (.ZN ( n758 ) , .I ( n812 ) ) ;
NR2D1BWP U1568 (.ZN ( n756 ) , .A1 ( n758 ) , .A2 ( n759 ) ) ;
CKND1BWP U1569 (.ZN ( n909 ) , .I ( cu1_counterChain_io_data_1_out_0_ ) ) ;
NR2D1BWP U1570 (.ZN ( n786 ) , .A1 ( n755 ) , .A2 ( n816 ) ) ;
HA1D0BWP U1571 (.S ( n785 ) , .A ( n757 ) , .B ( n756 ) , .CO ( n753 ) ) ;
NR2D1BWP U1572 (.ZN ( n814 ) , .A1 ( n816 ) , .A2 ( n758 ) ) ;
NR2D1BWP U1573 (.ZN ( n813 ) , .A1 ( n747 ) , .A2 ( n759 ) ) ;
FICIND1BWP U1604 (.S ( n872 ) , .CO ( n835 ) , .CIN ( n784 ) , .B ( n785 ) 
    , .A ( n786 ) ) ;
INVD1BWP U1605 (.ZN ( n894 ) , .I ( cu0_counterChain_io_data_0_out_2_ ) ) ;
CKND2D1BWP U1606 (.ZN ( n787 ) , .A1 ( n3 ) 
    , .A2 ( cu0_RegisterBlock_FF_io_data_out_2_ ) ) ;
OAI21D1BWP U1607 (.B ( n787 ) , .ZN ( n839 ) , .A1 ( n3 ) , .A2 ( n894 ) ) ;
INVD1BWP U1608 (.ZN ( n793 ) , .I ( n839 ) ) ;
IOA21D1BWP U1609 (.ZN ( n838 ) , .B ( n787 ) 
    , .A2 ( cu0_counterChain_io_data_1_out_2_ ) , .A1 ( cu0_T21_0_ ) ) ;
INVD1BWP U1610 (.ZN ( n790 ) , .I ( n838 ) ) ;
INVD1BWP U1612 (.ZN ( n899 ) , .I ( cu0_counterChain_io_data_1_out_1_ ) ) ;
ND2D1BWP U1613 (.ZN ( n788 ) , .A1 ( n3 ) 
    , .A2 ( cu0_RegisterBlock_FF_io_data_out_1_ ) ) ;
OAI21D1BWP U1614 (.B ( n788 ) , .ZN ( n819 ) , .A1 ( n3 ) , .A2 ( n899 ) ) ;
INVD1BWP U1615 (.ZN ( n795 ) , .I ( n819 ) ) ;
INVD1BWP U1616 (.ZN ( n895 ) , .I ( cu0_counterChain_io_data_0_out_1_ ) ) ;
OAI21D1BWP U1617 (.B ( n788 ) , .ZN ( n820 ) , .A1 ( n3 ) , .A2 ( n895 ) ) ;
INVD1BWP U1618 (.ZN ( n794 ) , .I ( n820 ) ) ;
INVD1BWP U1619 (.ZN ( n896 ) , .I ( cu0_counterChain_io_data_0_out_0_ ) ) ;
ND2D1BWP U1620 (.ZN ( n792 ) , .A1 ( n3 ) 
    , .A2 ( cu0_RegisterBlock_FF_io_data_out_0_ ) ) ;
CKND1BWP U1621 (.ZN ( n900 ) , .I ( cu0_counterChain_io_data_1_out_0_ ) ) ;
NR2D1BWP U1622 (.ZN ( n804 ) , .A1 ( n793 ) , .A2 ( n748 ) ) ;
NR2D1BWP U1623 (.ZN ( n822 ) , .A1 ( n748 ) , .A2 ( n794 ) ) ;
NR2D1BWP U1624 (.ZN ( n821 ) , .A1 ( n827 ) , .A2 ( n795 ) ) ;
FICIND1BWP U1628 (.S ( n868 ) , .CO ( n840 ) , .CIN ( n802 ) , .B ( n803 ) 
    , .A ( n804 ) ) ;
NR2D1BWP U974 (.ZN ( n713 ) , .A1 ( n827 ) , .A2 ( n790 ) ) ;
NR2D1BWP U975 (.ZN ( n714 ) , .A1 ( n794 ) , .A2 ( n795 ) ) ;
CKXOR2D1BWP U976 (.Z ( n803 ) , .A2 ( n714 ) , .A1 ( n713 ) ) ;
AN2D1BWP U977 (.Z ( n791 ) , .A2 ( n714 ) , .A1 ( n713 ) ) ;
NR2D1BWP U984 (.ZN ( n718 ) , .A1 ( n794 ) , .A2 ( n790 ) ) ;
XOR3D1BWP U985 (.Z ( n841 ) , .A3 ( n749 ) , .A1 ( n791 ) , .A2 ( n718 ) ) ;
NR2D1BWP U988 (.ZN ( n720 ) , .A1 ( n759 ) , .A2 ( n755 ) ) ;
OAI21D1BWP U989 (.B ( n753 ) , .ZN ( n721 ) , .A1 ( n758 ) , .A2 ( n752 ) ) ;
OAI31D1BWP U990 (.B ( n721 ) , .A3 ( n752 ) , .ZN ( n722 ) , .A2 ( n753 ) 
    , .A1 ( n758 ) ) ;
XOR3D1BWP U991 (.Z ( n843 ) , .A3 ( n722 ) , .A1 ( n835 ) , .A2 ( n720 ) ) ;
OA21D1BWP U1004 (.Z ( n816 ) , .B ( n754 ) , .A1 ( n3 ) , .A2 ( n909 ) ) ;
NR2D1BWP U1005 (.ZN ( n729 ) , .A1 ( n795 ) , .A2 ( n793 ) ) ;
XOR3D1BWP U1006 (.Z ( n845 ) , .A3 ( n841 ) , .A1 ( n840 ) , .A2 ( n729 ) ) ;
IND3D1BWP U1018 (.B2 ( n2 ) 
    , .B1 ( cu1_counterChain_CounterRC_config__stride_0_ ) , .ZN ( n901 ) 
    , .A1 ( cu0_counterChain_io_data_1_out_2_ ) ) ;
CKND1BWP U1019 (.ZN ( n836 ) , .I ( n846 ) ) ;
AO21D1BWP U1023 (.Z ( n1432 ) , .B ( n868 ) , .A1 ( n801 ) , .A2 ( n3 ) ) ;
OA21D1BWP U1043 (.Z ( n827 ) , .B ( n792 ) , .A1 ( n3 ) , .A2 ( n896 ) ) ;
IND3D1BWP U1044 (.B2 ( n2 ) 
    , .B1 ( cu1_counterChain_CounterRC_config__stride_0_ ) , .ZN ( n910 ) 
    , .A1 ( cu1_counterChain_io_data_1_out_2_ ) ) ;
AO21D1BWP U1047 (.Z ( n1436 ) , .B ( n872 ) , .A1 ( n783 ) , .A2 ( n3 ) ) ;
DFQD1BWP cu0_config__pipeStage_1_opB_value_reg_0_ (.Q ( cu0_T21_0_ ) 
    , .D ( n1 ) , .CP ( cu0_controlBlock_incXbar_net3602 ) ) ;
DFQD1BWP cu1_counterChain_CounterRC_config__stride_reg_0_ (
    .Q ( cu1_counterChain_CounterRC_config__stride_0_ ) , .D ( n1 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_1_counter_reg__ff_reg_0_ (
    .Q ( cu1_counterChain_io_data_1_out_0_ ) 
    , .D ( cu1_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_1_counter_reg__ff_reg_0_ (
    .Q ( cu0_counterChain_io_data_1_out_0_ ) 
    , .D ( cu0_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_1_counter_reg__ff_reg_2_ (
    .Q ( cu1_counterChain_io_data_1_out_2_ ) 
    , .D ( cu1_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_1_counter_reg__ff_reg_2_ (
    .Q ( cu0_counterChain_io_data_1_out_2_ ) 
    , .D ( cu0_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_counter_reg__ff_reg_0_ (
    .Q ( cu1_counterChain_io_data_0_out_0_ ) 
    , .D ( cu1_counterChain_CounterRC_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_counter_reg__ff_reg_0_ (
    .Q ( cu0_counterChain_io_data_0_out_0_ ) 
    , .D ( cu0_counterChain_CounterRC_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_counter_reg__ff_reg_2_ (
    .Q ( cu1_counterChain_io_data_0_out_2_ ) 
    , .D ( cu1_counterChain_CounterRC_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_counter_reg__ff_reg_2_ (
    .Q ( cu0_counterChain_io_data_0_out_2_ ) 
    , .D ( cu0_counterChain_CounterRC_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_1_counter_reg__ff_reg_1_ (
    .Q ( cu1_counterChain_io_data_1_out_1_ ) 
    , .D ( cu1_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_1_counter_reg__ff_reg_1_ (
    .Q ( cu0_counterChain_io_data_1_out_1_ ) 
    , .D ( cu0_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_counter_reg__ff_reg_1_ (
    .Q ( cu1_counterChain_io_data_0_out_1_ ) 
    , .D ( cu1_counterChain_CounterRC_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_counter_reg__ff_reg_1_ (
    .Q ( cu0_counterChain_io_data_0_out_1_ ) 
    , .D ( cu0_counterChain_CounterRC_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_0_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_0_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3515 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_1_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_1_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3512 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_2_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_2_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3509 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_3_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_3_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3506 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_1_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_1_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3512 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_2_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_2_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3509 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_0_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_0_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3515 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
assign io_status = 1'b0;
endmodule


