//
// Milkyway Hierarchical Verilog Dump:
// Generated on 08/06/2016 at 17:56:01
// Design Generated by Consolidated Verilog Reader
// File produced by Consolidated Verilog Writer
// Library Name :Plasticine
// Cell Name    :Plasticine
// Hierarchy delimiter:'/'
// Write Command : write_verilog /local/ssd/home/tianzhao/power_estimate_eg/plasticine/scripts/CU_power_area_estimate/post_pr_gatelevel_netlist/Plasticine.output.v
//


module SNPS_CLOCK_GATE_HIGH_SRAM_0_26 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_27 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_28 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_29 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_30 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_31 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_32 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_33 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_15 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_16 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_18 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_19 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_21 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_23 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_24 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_25 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_7 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_8 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_9 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_10 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_11 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_12 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_13 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_14 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD6BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_8 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_FF_1_4_20 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_Crossbar_1_0_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD12BWP latch (.Q ( ENCLK ) , .CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_1 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_2 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_4 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module SNPS_CLOCK_GATE_HIGH_SRAM_0_6 (CLK , EN , TE , ENCLK );
input  CLK ;
input  EN ;
input  TE ;
output ENCLK ;



CKLNQD1BWP latch (.CP ( CLK ) , .E ( EN ) , .TE ( TE ) ) ;
endmodule




module Plasticine (io_status , io_command , io_config_enable , reset , 
    clk );
output io_status ;
input  io_command ;
input  io_config_enable ;
input  reset ;
input  clk ;




SNPS_CLOCK_GATE_HIGH_SRAM_0_26 cu0_mem1_clk_gate_mem_reg_7_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N22 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_27 cu0_mem1_clk_gate_mem_reg_6_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N21 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_28 cu0_mem1_clk_gate_mem_reg_5_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N20 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_29 cu0_mem1_clk_gate_mem_reg_4_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N19 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_30 cu0_mem1_clk_gate_mem_reg_3_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N18 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_31 cu0_mem1_clk_gate_mem_reg_2_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N17 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_32 cu0_mem1_clk_gate_mem_reg_1_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N16 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_33 cu0_mem1_clk_gate_mem_reg_0_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N15 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_15 cu1_mem0_clk_gate_mem_reg_1_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N16 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_16 cu1_mem0_clk_gate_mem_reg_0_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N15 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_18 cu0_mem1_clk_gate_mem_reg_15_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N30 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_19 cu0_mem1_clk_gate_mem_reg_14_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N29 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_21 cu0_mem1_clk_gate_mem_reg_12_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N27 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_23 cu0_mem1_clk_gate_mem_reg_10_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N25 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_24 cu0_mem1_clk_gate_mem_reg_9_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N24 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_25 cu0_mem1_clk_gate_mem_reg_8_ (
    .CLK ( clk_G1IP ) , .EN ( cu0_mem0_N23 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_7 cu1_mem0_clk_gate_mem_reg_9_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N24 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_8 cu1_mem0_clk_gate_mem_reg_8_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N23 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_9 cu1_mem0_clk_gate_mem_reg_7_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N22 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_10 cu1_mem0_clk_gate_mem_reg_6_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N21 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_11 cu1_mem0_clk_gate_mem_reg_5_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N20 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_12 cu1_mem0_clk_gate_mem_reg_4_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N19 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_13 cu1_mem0_clk_gate_mem_reg_3_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N18 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_14 cu1_mem0_clk_gate_mem_reg_2_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N17 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_1 cu1_counterChain_CounterRC_1_counter_reg__clk_gate_ff_reg (
    .CLK ( CTS_ideal_clock1_CTO_delay11 ) , .EN ( n1 ) , .TE ( 1'b0 ), 
    .ENCLK ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_8 cu1_RegisterBlock_1_FF_1_clk_gate_ff_reg (
    .CLK ( clk_G1IP ) , .EN ( n10 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_FF_1_4_20 cu0_RegisterBlock_1_FF_1_clk_gate_ff_reg (
    .CLK ( clk_G1IP ) , .EN ( n9 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_Crossbar_1_0_1 cu0_controlBlock_incXbar_clk_gate_config__outSelect_3_reg (
    .CLK ( CTS_ideal_clock1_CTO_delay11 ) , 
    .EN ( cu0_controlBlock_incXbar_net3599 ) , .TE ( 1'b0 ), 
    .ENCLK ( cu0_controlBlock_incXbar_net3602 ) ) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_1 cu1_mem0_clk_gate_mem_reg_15_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N30 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_2 cu1_mem0_clk_gate_mem_reg_14_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N29 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_4 cu1_mem0_clk_gate_mem_reg_12_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N27 ) , .TE ( 1'b0 )) ;


SNPS_CLOCK_GATE_HIGH_SRAM_0_6 cu1_mem0_clk_gate_mem_reg_10_ (
    .CLK ( clk_G1IP ) , .EN ( cu1_mem1_N25 ) , .TE ( 1'b0 )) ;

OR2XD1BWP U5 (.Z ( n10 ) , .A2 ( cu0_T21_0_ ) , .A1 ( n1 ) ) ;
OR2XD1BWP U4 (.Z ( n9 ) , .A2 ( n1 ) , .A1 ( cu0_T21_0_ ) ) ;
FA1D0BWP U1602 (.CO ( n734 ) , .S ( n744 ) , .CI ( n742 ) , .B ( n743 ) 
    , .A ( n778 ) ) ;
FA1D0BWP U1587 (.CO ( n701 ) , .S ( n717 ) , .CI ( n715 ) , .B ( n716 ) 
    , .A ( n784 ) ) ;
CKBD16BWP CTS_ideal_clock1_CTO_delay1 (.Z ( CTS_ideal_clock1_CTO_delay11 ) 
    , .I ( clk ) ) ;
CKBD16BWP CKBD16BWP_G1IP (.Z ( clk_G1IP ) , .I ( clk ) ) ;
CKND4BWP U3 (.ZN ( n3 ) , .I ( cu0_T21_0_ ) ) ;
CKND0BWP U2 (.ZN ( n2 ) , .I ( n1 ) ) ;
CKBD3BWP U1 (.Z ( n1 ) , .I ( reset ) ) ;
NR2D1BWP U1698 (.ZN ( cu0_counterChain_CounterRC_counter_reg__net3515 ) 
    , .A1 ( n827 ) , .A2 ( cu0_counterChain_io_data_0_out_0_ ) ) ;
AOI221D1BWP U1699 (.C ( n827 ) , .B1 ( n826 ) , .B2 ( n825 ) 
    , .A2 ( cu0_counterChain_io_data_0_out_0_ ) 
    , .ZN ( cu0_counterChain_CounterRC_counter_reg__net3512 ) 
    , .A1 ( cu0_counterChain_io_data_0_out_1_ ) ) ;
CKND2D1BWP U1700 (.ZN ( n828 ) , .A1 ( cu0_counterChain_io_data_0_out_1_ ) 
    , .A2 ( cu0_counterChain_io_data_0_out_0_ ) ) ;
NR2D1BWP U1701 (.ZN ( cu0_counterChain_CounterRC_counter_reg__net3509 ) 
    , .A1 ( n828 ) , .A2 ( n827 ) ) ;
NR2D1BWP U1702 (.ZN ( cu0_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .A1 ( n832 ) , .A2 ( cu0_counterChain_io_data_1_out_0_ ) ) ;
AOI221D1BWP U1703 (.C ( n832 ) , .B1 ( n831 ) , .B2 ( n830 ) 
    , .A2 ( cu0_counterChain_io_data_1_out_0_ ) 
    , .ZN ( cu0_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .A1 ( cu0_counterChain_io_data_1_out_1_ ) ) ;
CKND2D1BWP U1704 (.ZN ( n833 ) , .A1 ( cu0_counterChain_io_data_1_out_1_ ) 
    , .A2 ( cu0_counterChain_io_data_1_out_0_ ) ) ;
NR2D1BWP U1705 (.ZN ( cu0_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .A1 ( n833 ) , .A2 ( n832 ) ) ;
NR2D1BWP U1706 (.ZN ( cu1_counterChain_CounterRC_counter_reg__net3515 ) 
    , .A1 ( n837 ) , .A2 ( cu1_counterChain_io_data_0_out_0_ ) ) ;
AOI221D1BWP U1707 (.C ( n837 ) , .B1 ( n836 ) , .B2 ( n835 ) 
    , .A2 ( cu1_counterChain_io_data_0_out_0_ ) 
    , .ZN ( cu1_counterChain_CounterRC_counter_reg__net3512 ) 
    , .A1 ( cu1_counterChain_io_data_0_out_1_ ) ) ;
CKND2D1BWP U1708 (.ZN ( n838 ) , .A1 ( cu1_counterChain_io_data_0_out_1_ ) 
    , .A2 ( cu1_counterChain_io_data_0_out_0_ ) ) ;
NR2D1BWP U1709 (.ZN ( cu1_counterChain_CounterRC_counter_reg__net3509 ) 
    , .A1 ( n838 ) , .A2 ( n837 ) ) ;
NR2D1BWP U1710 (.ZN ( cu1_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .A1 ( n842 ) , .A2 ( cu1_counterChain_io_data_1_out_0_ ) ) ;
AOI221D1BWP U1711 (.C ( n842 ) , .B1 ( n841 ) , .B2 ( n840 ) 
    , .A2 ( cu1_counterChain_io_data_1_out_0_ ) 
    , .ZN ( cu1_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .A1 ( cu1_counterChain_io_data_1_out_1_ ) ) ;
CKND2D1BWP U1712 (.ZN ( n843 ) , .A1 ( cu1_counterChain_io_data_1_out_1_ ) 
    , .A2 ( cu1_counterChain_io_data_1_out_0_ ) ) ;
NR2D1BWP U1713 (.ZN ( cu1_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .A1 ( n843 ) , .A2 ( n842 ) ) ;
ND2D1BWP U1714 (.ZN ( n846 ) , .A1 ( n847 ) , .A2 ( n849 ) ) ;
ND2D1BWP U1715 (.ZN ( n852 ) , .A1 ( n844 ) , .A2 ( n845 ) ) ;
NR2D1BWP U1716 (.ZN ( cu0_mem0_N15 ) , .A1 ( n846 ) , .A2 ( n852 ) ) ;
ND2D1BWP U1717 (.ZN ( n850 ) , .A1 ( n844 ) , .A2 ( n1338 ) ) ;
NR2D1BWP U1718 (.ZN ( cu0_mem0_N16 ) , .A1 ( n850 ) , .A2 ( n846 ) ) ;
ND2D1BWP U1719 (.ZN ( n853 ) , .A1 ( n1339 ) , .A2 ( n845 ) ) ;
NR2D1BWP U1720 (.ZN ( cu0_mem0_N17 ) , .A1 ( n853 ) , .A2 ( n846 ) ) ;
ND2D1BWP U1721 (.ZN ( n854 ) , .A1 ( n1339 ) , .A2 ( n1338 ) ) ;
NR2D1BWP U1722 (.ZN ( cu0_mem0_N18 ) , .A1 ( n854 ) , .A2 ( n846 ) ) ;
ND2D1BWP U1723 (.ZN ( n848 ) , .A1 ( n847 ) , .A2 ( n1340 ) ) ;
NR2D1BWP U1724 (.ZN ( cu0_mem0_N19 ) , .A1 ( n848 ) , .A2 ( n852 ) ) ;
NR2D1BWP U1725 (.ZN ( cu0_mem0_N20 ) , .A1 ( n848 ) , .A2 ( n850 ) ) ;
NR2D1BWP U1726 (.ZN ( cu0_mem0_N21 ) , .A1 ( n848 ) , .A2 ( n853 ) ) ;
NR2D1BWP U1727 (.ZN ( cu0_mem0_N22 ) , .A1 ( n848 ) , .A2 ( n854 ) ) ;
CKND2D1BWP U1728 (.ZN ( n851 ) , .A1 ( n1341 ) , .A2 ( n849 ) ) ;
NR2D1BWP U1729 (.ZN ( cu0_mem0_N23 ) , .A1 ( n851 ) , .A2 ( n852 ) ) ;
NR2D1BWP U1730 (.ZN ( cu0_mem0_N24 ) , .A1 ( n851 ) , .A2 ( n850 ) ) ;
NR2D1BWP U1731 (.ZN ( cu0_mem0_N25 ) , .A1 ( n851 ) , .A2 ( n853 ) ) ;
CKND2D1BWP U1732 (.ZN ( n855 ) , .A1 ( n1341 ) , .A2 ( n1340 ) ) ;
NR2D1BWP U1733 (.ZN ( cu0_mem0_N27 ) , .A1 ( n855 ) , .A2 ( n852 ) ) ;
NR2D1BWP U1734 (.ZN ( cu0_mem0_N29 ) , .A1 ( n855 ) , .A2 ( n853 ) ) ;
NR2D1BWP U1735 (.ZN ( cu0_mem0_N30 ) , .A1 ( n855 ) , .A2 ( n854 ) ) ;
ND2D1BWP U1736 (.ZN ( n858 ) , .A1 ( n859 ) , .A2 ( n861 ) ) ;
ND2D1BWP U1737 (.ZN ( n864 ) , .A1 ( n856 ) , .A2 ( n857 ) ) ;
NR2D1BWP U1738 (.ZN ( cu1_mem1_N15 ) , .A1 ( n858 ) , .A2 ( n864 ) ) ;
ND2D1BWP U1739 (.ZN ( n862 ) , .A1 ( n856 ) , .A2 ( n1342 ) ) ;
NR2D1BWP U1740 (.ZN ( cu1_mem1_N16 ) , .A1 ( n862 ) , .A2 ( n858 ) ) ;
ND2D1BWP U1741 (.ZN ( n865 ) , .A1 ( n1343 ) , .A2 ( n857 ) ) ;
NR2D1BWP U1742 (.ZN ( cu1_mem1_N17 ) , .A1 ( n865 ) , .A2 ( n858 ) ) ;
ND2D1BWP U1743 (.ZN ( n866 ) , .A1 ( n1343 ) , .A2 ( n1342 ) ) ;
NR2D1BWP U1744 (.ZN ( cu1_mem1_N18 ) , .A1 ( n866 ) , .A2 ( n858 ) ) ;
ND2D1BWP U1745 (.ZN ( n860 ) , .A1 ( n859 ) , .A2 ( n1344 ) ) ;
NR2D1BWP U1746 (.ZN ( cu1_mem1_N19 ) , .A1 ( n860 ) , .A2 ( n864 ) ) ;
NR2D1BWP U1747 (.ZN ( cu1_mem1_N20 ) , .A1 ( n860 ) , .A2 ( n862 ) ) ;
NR2D1BWP U1748 (.ZN ( cu1_mem1_N21 ) , .A1 ( n860 ) , .A2 ( n865 ) ) ;
NR2D1BWP U1749 (.ZN ( cu1_mem1_N22 ) , .A1 ( n860 ) , .A2 ( n866 ) ) ;
CKND2D1BWP U1750 (.ZN ( n863 ) , .A1 ( n1345 ) , .A2 ( n861 ) ) ;
NR2D1BWP U1751 (.ZN ( cu1_mem1_N23 ) , .A1 ( n863 ) , .A2 ( n864 ) ) ;
NR2D1BWP U1752 (.ZN ( cu1_mem1_N24 ) , .A1 ( n863 ) , .A2 ( n862 ) ) ;
NR2D1BWP U1753 (.ZN ( cu1_mem1_N25 ) , .A1 ( n863 ) , .A2 ( n865 ) ) ;
CKND2D1BWP U1754 (.ZN ( n867 ) , .A1 ( n1345 ) , .A2 ( n1344 ) ) ;
NR2D1BWP U1755 (.ZN ( cu1_mem1_N27 ) , .A1 ( n867 ) , .A2 ( n864 ) ) ;
NR2D1BWP U1756 (.ZN ( cu1_mem1_N29 ) , .A1 ( n867 ) , .A2 ( n865 ) ) ;
NR2D1BWP U1757 (.ZN ( cu1_mem1_N30 ) , .A1 ( n867 ) , .A2 ( n866 ) ) ;
ND3D1BWP U1621 (.ZN ( n845 ) , .A1 ( cu0_counterChain_io_data_0_out_0_ ) 
    , .A2 ( cu0_counterChain_io_data_1_out_0_ ) , .A3 ( cu0_T21_0_ ) ) ;
CKND1BWP U1622 (.ZN ( n1338 ) , .I ( n845 ) ) ;
ND3D1BWP U1623 (.ZN ( n857 ) , .A1 ( cu1_counterChain_io_data_1_out_0_ ) 
    , .A2 ( cu1_counterChain_io_data_0_out_0_ ) , .A3 ( cu0_T21_0_ ) ) ;
CKND1BWP U1624 (.ZN ( n1342 ) , .I ( n857 ) ) ;
OR2XD1BWP U1625 (.Z ( cu0_controlBlock_incXbar_net3599 ) , .A2 ( n1 ) 
    , .A1 ( io_config_enable ) ) ;
FICIND1BWP U1627 (.S ( n779 ) , .CO ( n738 ) , .CIN ( n773 ) , .B ( n777 ) 
    , .A ( n774 ) ) ;
AO21D1BWP U1628 (.Z ( n1343 ) , .B ( n787 ) , .A1 ( n779 ) , .A2 ( n3 ) ) ;
AO21D1BWP U1629 (.Z ( n1339 ) , .B ( n788 ) , .A1 ( n786 ) , .A2 ( n3 ) ) ;
NR2D1BWP U1630 (.ZN ( cu1_RegisterBlock_FF_1_net3515 ) , .A1 ( n1 ) 
    , .A2 ( n857 ) ) ;
NR2D1BWP U1631 (.ZN ( cu0_RegisterBlock_FF_1_net3515 ) , .A1 ( n1 ) 
    , .A2 ( n845 ) ) ;
INVD1BWP U1635 (.ZN ( n856 ) , .I ( n1343 ) ) ;
NR2D1BWP U1636 (.ZN ( cu1_RegisterBlock_FF_1_net3512 ) , .A1 ( n1 ) 
    , .A2 ( n856 ) ) ;
INVD1BWP U1637 (.ZN ( n844 ) , .I ( n1339 ) ) ;
NR2D1BWP U1638 (.ZN ( cu0_RegisterBlock_FF_1_net3512 ) , .A1 ( n1 ) 
    , .A2 ( n844 ) ) ;
CKND1BWP U1639 (.ZN ( n861 ) , .I ( n1344 ) ) ;
NR2D1BWP U1640 (.ZN ( cu1_RegisterBlock_FF_1_net3509 ) , .A1 ( n1 ) 
    , .A2 ( n861 ) ) ;
CKND1BWP U1642 (.ZN ( n849 ) , .I ( n1340 ) ) ;
NR2D1BWP U1643 (.ZN ( cu0_RegisterBlock_FF_1_net3509 ) , .A1 ( n1 ) 
    , .A2 ( n849 ) ) ;
FICIND1BWP U1644 (.S ( n732 ) , .CIN ( n790 ) 
    , .B ( cu1_RegisterBlock_FF_io_data_out_3_ ) 
    , .A ( cu1_RegisterBlock_FF_io_data_out_3_ ) ) ;
CKND1BWP U1648 (.ZN ( n859 ) , .I ( n1345 ) ) ;
NR2D1BWP U1649 (.ZN ( cu1_RegisterBlock_FF_1_net3506 ) , .A1 ( n859 ) 
    , .A2 ( n1 ) ) ;
CKND1BWP U1653 (.ZN ( n847 ) , .I ( n1341 ) ) ;
CKND1BWP U1657 (.ZN ( n829 ) , .I ( cu0_counterChain_io_data_1_out_2_ ) ) ;
CKND1BWP U1660 (.ZN ( n839 ) , .I ( cu1_counterChain_io_data_1_out_2_ ) ) ;
CKND2D1BWP U1511 (.ZN ( n679 ) , .A1 ( n3 ) 
    , .A2 ( cu0_RegisterBlock_FF_io_data_out_2_ ) ) ;
IOA21D1BWP U1512 (.ZN ( n712 ) , .B ( n679 ) 
    , .A2 ( cu0_counterChain_io_data_1_out_2_ ) , .A1 ( cu0_T21_0_ ) ) ;
CKND1BWP U1513 (.ZN ( n685 ) , .I ( n712 ) ) ;
IOA21D1BWP U1514 (.ZN ( n713 ) , .B ( n679 ) 
    , .A2 ( cu0_counterChain_io_data_0_out_2_ ) , .A1 ( cu0_T21_0_ ) ) ;
INVD1BWP U1515 (.ZN ( n831 ) , .I ( cu0_counterChain_io_data_1_out_1_ ) ) ;
ND2D1BWP U1516 (.ZN ( n680 ) , .A1 ( n3 ) 
    , .A2 ( cu0_RegisterBlock_FF_io_data_out_1_ ) ) ;
OAI21D1BWP U1517 (.B ( n680 ) , .ZN ( n783 ) , .A1 ( n3 ) , .A2 ( n831 ) ) ;
AN2XD1BWP U1518 (.Z ( n702 ) , .A2 ( n713 ) , .A1 ( n783 ) ) ;
CKND1BWP U1519 (.ZN ( n830 ) , .I ( cu0_counterChain_io_data_1_out_0_ ) ) ;
CKND2D1BWP U1520 (.ZN ( n681 ) , .A1 ( n3 ) 
    , .A2 ( cu0_RegisterBlock_FF_io_data_out_0_ ) ) ;
OAI21D1BWP U1521 (.B ( n681 ) , .ZN ( n781 ) , .A1 ( n830 ) , .A2 ( n3 ) ) ;
INVD1BWP U1522 (.ZN ( n826 ) , .I ( cu0_counterChain_io_data_0_out_1_ ) ) ;
OAI21D1BWP U1523 (.B ( n680 ) , .ZN ( n780 ) , .A1 ( n3 ) , .A2 ( n826 ) ) ;
CKND1BWP U1524 (.ZN ( n825 ) , .I ( cu0_counterChain_io_data_0_out_0_ ) ) ;
OAI21D1BWP U1525 (.B ( n681 ) , .ZN ( n782 ) , .A1 ( n825 ) , .A2 ( n3 ) ) ;
AN4D1BWP U1526 (.Z ( n784 ) , .A4 ( n782 ) , .A3 ( n780 ) , .A2 ( n781 ) 
    , .A1 ( n783 ) ) ;
CKND1BWP U1527 (.ZN ( n683 ) , .I ( n782 ) ) ;
CKND2D1BWP U1528 (.ZN ( n682 ) , .A1 ( n783 ) , .A2 ( n780 ) ) ;
OAI32D1BWP U1529 (.B1 ( n682 ) , .B2 ( n664 ) , .A3 ( n683 ) , .A2 ( n685 ) 
    , .A1 ( n664 ) , .ZN ( n716 ) ) ;
AN2XD1BWP U1530 (.Z ( n715 ) , .A2 ( n713 ) , .A1 ( n781 ) ) ;
CKND1BWP U1531 (.ZN ( n684 ) , .I ( n780 ) ) ;
AOI211D1BWP U1532 (.C ( n684 ) , .B ( n685 ) , .ZN ( n700 ) , .A2 ( n782 ) 
    , .A1 ( n783 ) ) ;
FA1D1BWP U1559 (.S ( n703 ) , .CI ( n700 ) , .B ( n701 ) , .A ( n702 ) ) ;
CKND2D1BWP U1560 (.ZN ( n792 ) , .A1 ( cu0_T21_0_ ) , .A2 ( n703 ) ) ;
IOA21D1BWP U1561 (.ZN ( n1341 ) , .B ( n792 ) , .A2 ( n3 ) , .A1 ( n704 ) ) ;
CKND2D1BWP U1562 (.ZN ( n705 ) , .A1 ( n3 ) 
    , .A2 ( cu1_RegisterBlock_FF_io_data_out_2_ ) ) ;
IOA21D1BWP U1563 (.ZN ( n739 ) , .B ( n705 ) 
    , .A2 ( cu1_counterChain_io_data_1_out_2_ ) , .A1 ( cu0_T21_0_ ) ) ;
CKND1BWP U1564 (.ZN ( n710 ) , .I ( n739 ) ) ;
IOA21D1BWP U1565 (.ZN ( n740 ) , .B ( n705 ) 
    , .A2 ( cu1_counterChain_io_data_0_out_2_ ) , .A1 ( cu0_T21_0_ ) ) ;
INVD1BWP U1566 (.ZN ( n841 ) , .I ( cu1_counterChain_io_data_1_out_1_ ) ) ;
ND2D1BWP U1567 (.ZN ( n706 ) , .A1 ( n3 ) 
    , .A2 ( cu1_RegisterBlock_FF_io_data_out_1_ ) ) ;
OAI21D1BWP U1568 (.B ( n706 ) , .ZN ( n777 ) , .A1 ( n3 ) , .A2 ( n841 ) ) ;
AN2XD1BWP U1569 (.Z ( n735 ) , .A2 ( n740 ) , .A1 ( n777 ) ) ;
CKND1BWP U1570 (.ZN ( n840 ) , .I ( cu1_counterChain_io_data_1_out_0_ ) ) ;
CKND2D1BWP U1571 (.ZN ( n707 ) , .A1 ( n3 ) 
    , .A2 ( cu1_RegisterBlock_FF_io_data_out_0_ ) ) ;
OAI21D1BWP U1572 (.B ( n707 ) , .ZN ( n775 ) , .A1 ( n840 ) , .A2 ( n3 ) ) ;
INVD1BWP U1573 (.ZN ( n836 ) , .I ( cu1_counterChain_io_data_0_out_1_ ) ) ;
OAI21D1BWP U1574 (.B ( n706 ) , .ZN ( n774 ) , .A1 ( n3 ) , .A2 ( n836 ) ) ;
CKND1BWP U1575 (.ZN ( n835 ) , .I ( cu1_counterChain_io_data_0_out_0_ ) ) ;
OAI21D1BWP U1576 (.B ( n707 ) , .ZN ( n776 ) , .A1 ( n835 ) , .A2 ( n3 ) ) ;
AN4D1BWP U1577 (.Z ( n778 ) , .A4 ( n776 ) , .A3 ( n774 ) , .A2 ( n775 ) 
    , .A1 ( n777 ) ) ;
AN4D1BWP U1578 (.Z ( n726 ) , .A4 ( n776 ) , .A3 ( n774 ) , .A2 ( n777 ) 
    , .A1 ( n739 ) ) ;
CKND1BWP U1579 (.ZN ( n773 ) , .I ( n776 ) ) ;
CKND2D1BWP U1580 (.ZN ( n708 ) , .A1 ( n777 ) , .A2 ( n774 ) ) ;
OAI32D1BWP U1581 (.B1 ( n708 ) , .B2 ( n726 ) , .A3 ( n773 ) , .A2 ( n710 ) 
    , .A1 ( n726 ) , .ZN ( n743 ) ) ;
AN2XD1BWP U1582 (.Z ( n742 ) , .A2 ( n740 ) , .A1 ( n775 ) ) ;
CKND1BWP U1583 (.ZN ( n709 ) , .I ( n774 ) ) ;
AOI211D1BWP U1584 (.C ( n709 ) , .B ( n710 ) , .ZN ( n733 ) , .A2 ( n776 ) 
    , .A1 ( n777 ) ) ;
FICOND1BWP U1586 (.S ( n714 ) , .CON ( n795 ) , .CI ( n711 ) , .B ( n712 ) 
    , .A ( n713 ) ) ;
CKND2D1BWP U1588 (.ZN ( n803 ) , .A1 ( cu0_T21_0_ ) , .A2 ( n717 ) ) ;
CKND2D1BWP U1597 (.ZN ( n737 ) , .A1 ( n732 ) , .A2 ( n3 ) ) ;
FA1D1BWP U1598 (.S ( n736 ) , .CI ( n733 ) , .B ( n734 ) , .A ( n735 ) ) ;
CKND2D1BWP U1599 (.ZN ( n789 ) , .A1 ( cu0_T21_0_ ) , .A2 ( n736 ) ) ;
ND2D1BWP U1600 (.ZN ( n1345 ) , .A1 ( n737 ) , .A2 ( n789 ) ) ;
FICOND1BWP U1601 (.S ( n741 ) , .CON ( n790 ) , .CI ( n738 ) , .B ( n739 ) 
    , .A ( n740 ) ) ;
CKND2D1BWP U1603 (.ZN ( n804 ) , .A1 ( cu0_T21_0_ ) , .A2 ( n744 ) ) ;
XOR3D1BWP U972 (.Z ( n786 ) , .A3 ( n781 ) , .A1 ( n783 ) , .A2 ( n780 ) ) ;
MAOI222D1BWP U974 (.ZN ( n649 ) , .C ( n781 ) , .B ( n780 ) , .A ( n783 ) ) ;
CKND1BWP U975 (.ZN ( n711 ) , .I ( n649 ) ) ;
INR2D1BWP U976 (.B1 ( n1 ) , .ZN ( n834 ) 
    , .A1 ( cu1_counterChain_CounterRC_config__stride_0_ ) ) ;
CKND1BWP U977 (.ZN ( n704 ) , .I ( n795 ) ) ;
IND3D1BWP U986 (.B2 ( n839 ) 
    , .B1 ( cu1_counterChain_CounterRC_config__stride_0_ ) , .ZN ( n842 ) 
    , .A1 ( n1 ) ) ;
IND2D1BWP U987 (.ZN ( n827 ) , .B1 ( n834 ) 
    , .A1 ( cu0_counterChain_io_data_0_out_2_ ) ) ;
IND2D1BWP U1000 (.ZN ( n837 ) , .B1 ( n834 ) 
    , .A1 ( cu1_counterChain_io_data_0_out_2_ ) ) ;
ND3D1BWP U1001 (.ZN ( n832 ) 
    , .A1 ( cu1_counterChain_CounterRC_config__stride_0_ ) , .A2 ( n829 ) 
    , .A3 ( n2 ) ) ;
AOI22D1BWP U1002 (.A2 ( n776 ) , .A1 ( n777 ) , .ZN ( n656 ) , .B1 ( n775 ) 
    , .B2 ( n774 ) ) ;
NR2D1BWP U1003 (.ZN ( n787 ) , .A1 ( n778 ) , .A2 ( n656 ) ) ;
AOI22D1BWP U1004 (.A2 ( n782 ) , .A1 ( n783 ) , .ZN ( n657 ) , .B1 ( n781 ) 
    , .B2 ( n780 ) ) ;
NR2D1BWP U1005 (.ZN ( n788 ) , .A1 ( n784 ) , .A2 ( n657 ) ) ;
IOA21D1BWP U1006 (.ZN ( n1344 ) , .B ( n804 ) , .A2 ( n741 ) , .A1 ( n3 ) ) ;
IOA21D1BWP U1007 (.ZN ( n1340 ) , .B ( n803 ) , .A2 ( n714 ) , .A1 ( n3 ) ) ;
AN4D1BWP U1035 (.Z ( n664 ) , .A4 ( n782 ) , .A3 ( n780 ) , .A2 ( n783 ) 
    , .A1 ( n712 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_0_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_0_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3515 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_1_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_1_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3512 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_2_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_2_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3509 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_counterChain_CounterRC_1_counter_reg__ff_reg_1_ (
    .Q ( cu0_counterChain_io_data_1_out_1_ ) 
    , .D ( cu0_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_counter_reg__ff_reg_0_ (
    .Q ( cu1_counterChain_io_data_0_out_0_ ) 
    , .D ( cu1_counterChain_CounterRC_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_counter_reg__ff_reg_0_ (
    .Q ( cu0_counterChain_io_data_0_out_0_ ) 
    , .D ( cu0_counterChain_CounterRC_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_counter_reg__ff_reg_2_ (
    .Q ( cu1_counterChain_io_data_0_out_2_ ) 
    , .D ( cu1_counterChain_CounterRC_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_counter_reg__ff_reg_2_ (
    .Q ( cu0_counterChain_io_data_0_out_2_ ) 
    , .D ( cu0_counterChain_CounterRC_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_1_counter_reg__ff_reg_0_ (
    .Q ( cu1_counterChain_io_data_1_out_0_ ) 
    , .D ( cu1_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_1_counter_reg__ff_reg_2_ (
    .Q ( cu1_counterChain_io_data_1_out_2_ ) 
    , .D ( cu1_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_1_counter_reg__ff_reg_0_ (
    .Q ( cu0_counterChain_io_data_1_out_0_ ) 
    , .D ( cu0_counterChain_CounterRC_1_counter_reg__net3515 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_1_counter_reg__ff_reg_2_ (
    .Q ( cu0_counterChain_io_data_1_out_2_ ) 
    , .D ( cu0_counterChain_CounterRC_1_counter_reg__net3509 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_counter_reg__ff_reg_1_ (
    .Q ( cu1_counterChain_io_data_0_out_1_ ) 
    , .D ( cu1_counterChain_CounterRC_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu0_counterChain_CounterRC_counter_reg__ff_reg_1_ (
    .Q ( cu0_counterChain_io_data_0_out_1_ ) 
    , .D ( cu0_counterChain_CounterRC_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFKCNQD1BWP cu1_counterChain_CounterRC_1_counter_reg__ff_reg_1_ (
    .Q ( cu1_counterChain_io_data_1_out_1_ ) 
    , .D ( cu1_counterChain_CounterRC_1_counter_reg__net3512 ) 
    , .CN ( 1'b1 )
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu1_counterChain_CounterRC_config__stride_reg_0_ (
    .Q ( cu1_counterChain_CounterRC_config__stride_0_ ) , .D ( n1 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_config__pipeStage_1_opB_value_reg_0_ (.Q ( cu0_T21_0_ ) 
    , .D ( n1 ) , .CP ( cu0_controlBlock_incXbar_net3602 ) ) ;
DFQD1BWP cu1_RegisterBlock_FF_ff_reg_3_ (
    .Q ( cu1_RegisterBlock_FF_io_data_out_3_ ) 
    , .D ( cu1_RegisterBlock_FF_1_net3506 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_0_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_0_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3515 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_1_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_1_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3512 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
DFQD1BWP cu0_RegisterBlock_FF_ff_reg_2_ (
    .Q ( cu0_RegisterBlock_FF_io_data_out_2_ ) 
    , .D ( cu0_RegisterBlock_FF_1_net3509 ) 
    , .CP ( cu1_counterChain_CounterRC_1_counter_reg__net3518 ) ) ;
assign io_status = 1'b0;
endmodule


